### ISSUE TITLE
[Enhancement] Ore-Based Module

### ISSUE THREAD

**Issue by thatsIch** [RS485/LogisticsPipes#10]
The mod-based itemsink module gave me an idea for the ore-based itemsink. I think there is something called an ore-lexikon where each mod can enter its own worldgen and declare it as an ore. 

Generally the module itself should have less priority than a normal itemsink so that you can re-route the item if there is something special to do with it.
## 

offtop: whats better: posting here or posting on the "original" github of LP?

**Comment by keplersj** [comment]
How about an add-on pipe for OmniTools, like the Bee pipe for Forestry. That works like the Lexicon except slightly backwards. Pulling in anything that belongs to same Forge/Ore Dictionary as a defined item.

Working: The GUI would look kinda like the Lexicon where you can put in an item and the GUI will tell you what Dictionary it belongs to if any.

An advanced (endgame) version: A module (instead of a pipe) that could sink multiple dictionaries. Great for sorting metals, circuits, gems, etc. from multiple mods. (GregTech...)

**Comment by bziemons** [comment]
Something like that is on the way. Named "Advanced Item Sink Module".

**Comment by ruifung** [comment]
This probably should be closed to clean up the open issues list.

**Comment by keplersj** [comment]
That might be best seeing as my idea would no longer be applicable.
