### ISSUE TITLE
Missing texture (Upgrade Modue Upgrade)

### ISSUE THREAD

**Issue by Lightone** [RS485/LogisticsPipes#1003]
In the log appear that info 
`[20:16:35] [Client thread/ERROR]: Using missing texture, unable to load logisticspipes:textures/items/itemUpgrade/LogicController.png, java.io.FileNotFoundException
[20:16:35] [Client thread/ERROR]: Using missing texture, unable to load logisticspipes:textures/items/itemUpgrade/UpgradeModule.png, java.io.FileNotFoundException
[20:16:36] [Client thread/ERROR]: Using missing texture, unable to load logisticspipes:textures/items/ItemPipeSignCreator.png, java.io.FileNotFoundException`

i use the last version logisticspipes-0.9.3.121

[Error texture Imagen](http://i.imgur.com/sUdB9Cc.png)

**Comment by hron84** [comment]
Did you tried to re-download the affected version of Logistics Pipes from the [original source](http://ci.rs485.network/job/LogisticsPipes-0.9-mc17-bc7/121/artifact/build/libs/logisticspipes-0.9.3.121.jar)? It is important, if you downloaded it from some unofficial sources (other than Curse, ATLauncher or the dev's own Jenkins) it could be damaged. Please, try using the link in my comment to re-download the JAR, and re-test it. If the texture is still missing, please let us know.

Btw, as far as I know, Upgrade Module Upgrade is a WIP item, so it could be possible it is intentional.

**Comment by SonOfTheStars** [comment]
@hron84 @Lightone In deed this is intentional!
The upgrade Module Upgrade is a placeholder Item for a WIP type of Item. it has yet to be provided with a Texture.

Thanks for Reporting!
