### ISSUE TITLE
[Question] How do combine multiple LP networks via the logistics item cards?

### ISSUE THREAD

**Issue by ghost** [RS485/LogisticsPipes#1046]
If want to combine LP networks in three locations using logistics item cards, can I use a shared connection (hook each section to a common ender chest color combo), or do I have to chain them (link network 1 to network 2 and then link network 2 to network 3)?
If I need to do separate connections, can I use a common transfer inventory? (I'm playing with the TARDIS mod and there's no direct LP support, but there is a chest-seized shared inventory I can access from all over the TARDIS.)

**Comment by hron84** [comment]
For connecting with TARDIS, IIRC there is something like inventory connector or similar, check how you can integrate two LP system with Ender Chests, there is a bunch of tutorials out there about this. I suppose this technique should work with TARDIS' own shared inventory.

**Comment by ghost** [comment]
Thanks. I was being lazy. The shared inventory can be used for the inventory connectors, with a place to link the sub-systems together. It does appear to be slow, though.

**Comment by hron84** [comment]
I think the bottleneck in the speed is TARDIS. Maybe you will have a better performance if you use EnderStorage Ender Chests or Tesserracts. In the latter case, please also look for how it is possible since as far as I remember putting default routing / extraction pipes to the sides is not sufficient. 

You can also check out EnderIO Dimensional Transciever, which is also a shared invnetory, but it has a bit better performance.
