### ISSUE TITLE
Enchanted books

### ISSUE THREAD

**Issue by chack1172** [RS485/LogisticsPipes#1092]
Is it possible to insert all enchanted books in a chest and all weapons (enchanted or not) in another with logistics pipes?

**Comment by hron84** [comment]
There is an enchantment module that helps you to route items, though I did not use it yet, I guess you can route enchanted books with this. For weapons, you have to use a Fuzzy upgrade for your item sink pipe (technically, the basic LP pipe). After applying Fuzzy upgrade you can specify "Ignore NBT" on the GUI. 

If you have no problem with breaking the routing of normal books, you can also use Fuzzy upgrades to route enchanted books because enchanted books are basically normal, unenchanted books with NBT data. So, you can route all books into "enchanted books" storage with a basic itemsink and a fuzzy upgrade.

But please do not use GitHub issues for asking gameplay questions. I recommend you to use the [corresponding MCF forum](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1289546-buildcraft-logistics-pipes) about the mod to ask questions like this. GitHub issues are for bugs or crashes in the mod.

**Comment by bziemons** [comment]
Thanks @hron84
