### ISSUE TITLE
Crafting pipes dont examine the contents of a machine on world restart.

### ISSUE THREAD

**Issue by d1223m** [RS485/LogisticsPipes#112]
LP 0.7.3.dev.565
If a crafting pipe requests a bunch of items and then the world restarts, it re-requests all the items instead of checking the attached inventory for what is already in there.

**Comment by AartBluestoke** [comment]
a) in general, the crafting pipe has no idea if the items in there already have a purpose.
b) people often deliberately have pre-crafted items on the output so that requests can be serviced quickly (with replacements slowly re-crafted).
c) sometimes manual crafting is done on a machine with a crafting pipe on it
d) the internal inventory of many machines can't be extracted from, as the output slot(s) are what is visible for extraction
e) all the above point ignore satellite pipes, which result in items being in no detectable inventory.

Perhaps a crafting pipe could have a "buffer", where it deliberately pre-crafts items, but then extracts the rest of the output and ingredients?

**Comment by davboecki** [comment]
The Cleanup upgrade should fix this.
