### ISSUE TITLE
LogisticsPipes/AppliedEnergistics auto-crafting

### ISSUE THREAD

**Issue by ghost** [RS485/LogisticsPipes#1212]
Hi! I have a hybrid system with Logistics and Applied but the two system cannot craft between they, for example if I want to craft a thing that should crafted via appliedenergistics, logistics pipes can't see it and viceversa!
it's a useful thing and the community would appreciate it a lot
I've created the same Feature request on the Applied repo but they closed the issues! Can you guys add this feature?

**Comment by davboecki** [comment]
To put it simple no, at least not in the near future. 
This has been a request for several years and it is sadly not as simple as writing two interfaces and be done with it. 
The fundamental problem is that crafting tasks are precalculated. And that calculation depends highly on LP knowing exactly what is available for which crafter. Writing a compatibility layer between LP and AE or RS would involve us recreating parts of that mod so that we can handle all the different aspects of crafting. 
And I'm sorry to say, that is just way too much and there are higher things on our todo list for the moments when we have time to work on this mod, as our time is becoming more and more limited.

**Comment by ghost** [comment]
Ok, thank you very much, but I remember that with the old AE was able to craft with logistics

**Comment by davboecki** [comment]
Well, what you could do is trigger a crafting task inside LP but nothing more there was no real compatibility in the sense of part of the craft was done in LP and the other was done in AE and so on.

**Comment by ghost** [comment]
AE2 Doesn't see any crafting if I connect it to logistics :C So sad

**Comment by hron84** [comment]
Just an idea, but if you share inventory between two mods (LP can read it from RS, and LP provides the inventory of the network to RS) then you could rely on the other partner to do the crafting request on its own based on infos available, right? This is how e.g. RS works with compacting storage drawers that do some basic crafting too. 

The only problem is I can figure if there's some delivery problem on whatever side but it could happen independent from the interop.

**Comment by ghost** [comment]
You mean refined storage?

**Comment by hron84** [comment]
yep, RS=Refined Storage. I know it better than AE, but AFAIK they share same idea about crafting.
