### ISSUE TITLE
Create in-game item that replaces the wiki for now

### ISSUE THREAD

**Issue by bziemons** [RS485/LogisticsPipes#1242]
Before our first CurseForge release and transition into beta, we should give players some item that advises them how to use the compiler and the programmer item.
Also included should be why there are no mk2/mk3 modules/pipes anymore and that they can be mimicked with upgrades.

Related: #691

**Comment by dblsaiko** [comment]
We could do the same here as I did for Better With Mods ([package here](https://gitlab.com/BetterWithMods/1.12/BetterWithMods/tree/1.12/src/main/java/betterwithmods/manual)), just completely rip the [RTFM](https://minecraft.curseforge.com/projects/rtfm) mod and adjust it to work in LP. It's MIT, so it shouldn't be a problem. Allows you to write docs in Markdown, which is great.

**Comment by bziemons** [comment]
not in this issue, but maybe in a follow-up ?

**Comment by davboecki** [comment]
I don't know about the API part or Items of that mod, but the rendering and GUI stuff would probably be a good candidate for an item inside LP. But like zorro said, not in this issue. I will create a followup Issue and include that comment inside that issue, once this one is closed.

**Comment by hron84** [comment]
You should definitely check [Patchouli](https://minecraft.curseforge.com/projects/patchouli) too, it has a nice way to provide documentation - IIRC without messing with the API too much.

GitHub repo: https://github.com/Vazkii/Patchouli

It is not promoted as much, but it has a Wiki too.

**Comment by dblsaiko** [comment]
Yeah, but looks like you need that mod installed to use the documentation. Which may or may not be a good idea, idk. (that's why I copied RTFM's code instead of just depending on it)

**Comment by hron84** [comment]
AFAIK Deep Mob Learning made a way to check if Patchoui is installed and it can add its manual or added a fake book item with lore "install Patchouli if you need a manual" with same item icon and name that provided by the Patchoui book.

Copying a code from other mods is risky, if code in RTFM gets updated it's too easy to forget updating it in any including mod. Plus, updating RTFM code requires a version bump from the hosting mod regardless if the mod itself does not got any improvement since the last release. With a crash-fixing update it has to be planned. 

I'd rather recommend you to **not** include RTFM code inside LP, instead soft-depend or hard-depend on the mod that provides you a way to include manual. It could be more safe and less error-prone.

**Comment by hron84** [comment]
If you copy the code, you should rather use git submodules and hack the buildsystem to include the source paths you need for it because it could make easier building updated LP  artifacts based on an updated external code.

**Comment by bziemons** [comment]
Fixed by #1243
