### ISSUE TITLE
[1.12.2] Pipe plugs don't function

### ISSUE THREAD

**Issue by ie04** [RS485/LogisticsPipes#1252]
BC pipe plugs don't appear to work. This feature used to work in the 1.7.10 version. I'm aware of the Disconnection Upgrade, but applying it on any pipe also yields nothing.

**Comment by davboecki** [comment]
At the moment we do not plan to bring back BC pipe plug support. 
If the disconnection upgrades don't work, then that is a bug that needs to be fixed.

**Comment by dblsaiko** [comment]
Since BC is switching to Fabric, I don't see it happening in the future either (unless we port this to Fabric aswell, which I wouldn't be against ;) )

**Comment by bziemons** [comment]
@therealfarfetchd could you elaborate why you think it would be a good idea to move away from Forge?

**Comment by dblsaiko** [comment]
Mainly said that because I've switched all my projects to use Fabric, but here's some of the reasons why I prefer it over Forge:

- I've only had problems with Forge's dev env for 1.13+. Breakpoints not working sometimes, hotswapping being kinda wonky (and having to run `gradle build` to swap assets instead of just being able to hit ctrl+f9). This comes mainly due to the fact that the game needs to be run through gradle since the new FML doesn't like appending mods to the classpath, like running from the IDE does it (I've tried fixing that for the mod I was writing code for, but didn't succeed because something else broke, yay)  
Meanwhile, Fabric's dev plugin, while definitely not perfect (for example, you need to still decompile the game source manually if you want it (which you probably want since you can't do stuff such as looking up usages for compiled files), and then attach it through the IDE manually each time you update your mappings), has been a way better experience than both ForgeGradle 2.0 and 3.0
- It has really nice rendering extensions [[documentation](https://fabricmc.net/wiki/documentation:rendering)], which means we could ditch CCL depending on what it's used for outside of model loading (well, we'd have to anyway).
- Builtin mixin support, which is not as tedious to use as ASM if you need it
- It updates pretty fast to every game release, and updating to snapshots means you have more time to adjust to changes instead of having to adjust to every change between major versions at once
- The project is open source and community driven, and not as incredibly strict when it comes to PRs
