### ISSUE TITLE
polimorfic item sink not working correcly with drawer controller ( locked drawers with 0 items)

### ISSUE THREAD

**Issue by mikiones** [RS485/LogisticsPipes#1267]
if locked drawers is emptied, the polimorfic item sink stops route to that inventory

**Comment by Anaksanamune** [comment]
Have the same issue, easy to fix, just set the connected provider to "leave 1 item per type" so the drawer is never fully emptied.

**Comment by dblsaiko** [comment]
This is expected behavior because of how polymorphic sinks work (will only accept items based on attached inventory, of course if everything gets pulled out, it won't accept that item anymore), and the way @Anaksanamune uses them is the correct way (or at least, one way) to make it work as you want it to.
