### ISSUE TITLE
Auto output from GT do not is pushed into logistics pipe, 

### ISSUE THREAD

**Issue by mikiones** [RS485/LogisticsPipes#1270]
![image](https://user-images.githubusercontent.com/1821412/59565414-4ff64f80-904b-11e9-9320-26c903f90792.png)

when hopper is feeding logistics pipe works just fine. but not from GT machine

**Comment by davboecki** [comment]
We need more info on this one, as I have no idea how GT machines work.

Do all of them possess the ability to auto extract? 
Is that configurable so that you can extract from them, but they don't autoeject?

This is not a bug but more a compatibility thing as the only things currently allowed to push items into the "inventory" of LP pipes is the MC Hopper and BC pipes, and TD Ducts should also be able to send items into the LP network. 

For Reference: 
* https://github.com/RS485/LogisticsPipes/blob/dev-mc1122/src/main/kotlin/network/rs485/logisticspipes/proxy/PipeInventoryConnectionChecker.kt
* https://github.com/RS485/LogisticsPipes/blob/dev-mc1122/common/logisticspipes/proxy/buildcraft/BuildCraftProxy.java#L43

**Comment by mikiones** [comment]
thy have 2 buttons red and blue ( blue for liquid) if it on will push item to aj inventory like hopper does.

it was working before, so this is new issue.  every machine has it

**Comment by davboecki** [comment]
Like I said, that it was working was not intended at that time so it was a bug that is was working. Now there is a system in place for it to be intended to work. We just need to whitelist it as I referenced in my comment above.

**Comment by mikiones** [comment]
i see

**Comment by Hasunemiku2015** [comment]
Hmm, so i was putting a supplier pipe onto a EU2 overclock generator , i ask it to keep 1 stack of sugarcane in it at all times, with all of the different mode tested , it either not request sugarcane or it over request than the sugarcane is not entering the generator and flowing in pipes, how to solve

**Comment by bziemons** [comment]
@Hasunemiku2015 that is unrelated to this issue. Open a new one, if you think there is a problem. But be sure to have the newest LP version.

**Comment by davboecki** [comment]
Please check if this works with build 162.

**Comment by mikiones** [comment]
its working now.
