### ISSUE TITLE
Add fluid supplier/provider modules which can be placed in chassis pipes

### ISSUE THREAD

**Issue by ndsf** [RS485/LogisticsPipes#1324]
Pipes can easily get messed up when trying to supply a machine with mutiple types of fluids and extracting products out of it. It would be nice if these can get handled with a chassis pipe.

**Comment by davboecki** [comment]
We intentionally did not add chassis pipes and modules for fluids because of how the fluid system works. Each pipe has a tank on the side which is used to store the fluid before it is passed to the machine. Like every other pipe does it. So it would lead to high complications if you could use multiple fluids to sink and supply on the same pipe.

**Comment by hron84** [comment]
It depends on the TileEntity that contains the tank(s). Tinker's tank could allow multiple fluids. Refined Storage / Applied Energistics systems could allow multiple fluids. GregTech machines could contain multiple fluids in a single block (but in different tanks). Same for Nuclearcraft machines. I do not see it as pure evil, but it would be complicated to implement.

**Comment by hubertnnn** [comment]
If you think supporting multiple fluids is too hard for now, you could always make the modules and add a limit to one per chasis pipe (with proper description). 
It would be a step towards full fluid handling and it will allow machines that use fluids like forestry carpenter, or most gregtech machines to be both supplied with fluids and autocrafting at the same time.

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
