### ISSUE TITLE
work interrupted when game is closed

### ISSUE THREAD

**Issue by eduardopilati** [RS485/LogisticsPipes#1343]
Hello,

Several times I found material inside my furnaces, I never understood how it was happening but today I had the proof.

After ordering some items by request pipe and closing the game these items never end.

scenario:

- request 5 terminus module in a request pipe
- 3 terminus module are delivered
- Game closed
- Open game
- 2 FPGAs remain inside the furnace, and terminus modules are never delivered.

I'm using version 195

**Comment by davboecki** [comment]
This is intended behaviour, restarting the game or the server clears out the order queue of all pipes inside the game.

**Comment by nyasara** [comment]
Is there any way this could be a setting or something? I'm running a rather large, complex setup in Omnifactory with LP, and when I have to restart my server, I can end up with clogs all over the system from half-completed crafts. One can always choose to break/replace a pipe if you need to clear its order queue (or maybe an option in the pipe controller GUI to delete orders). But just clearing everything out without considering the leftovers is rather aggressive.

**Comment by dblsaiko** [comment]
Imo anything going on in the world should not be affected by a server restart. A dedicated way to reset the network? Sure. But the network should save and restore its state to/from disk so that server restarts are "seamless", because there's not necessarily a way to prevent those as a player.

What's the reason for this being intended behavior?

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
