### ISSUE TITLE
[Suggestion] Crafting times

### ISSUE THREAD

**Issue by Rectorian** [RS485/LogisticsPipes#1353]
Hi, I've been playing a lot with LP and its definitely one of my favorite mods since forever. I do have a suggestion that could solve some problems with longer auto-crafts. Add the ability to detect or have a player specify a crafting time. This would allow the system to not "time-out" on a crafting process that takes a decent amount of time *cough* greg-tech electric blast furnace *cough*.

**Comment by Rectorian** [comment]
Wanted to add some helpful info/workaround for people also trying to use LP for autocrafting EBF alloys. Originally I used a chassis pipe with crafting modules connected to the item output hatch and then used satellite pipes to send the items to multiple item input hatches. For some reason, if you want to craft something that takes a while, the recipe would timeout and eventually it would just send the requested items to a default route instead of your requester or remote orderer. To fix this problem, I accidentally discovered that if you instead attach the chassis pipes with your crafting recipes to a chest, it would not cause this timeout problem and would send requested items to their correct destinations and not default or item-sink routes.

**Comment by davboecki** [comment]
Thanks for that information. That could actually help us pinpoint the root cause of the problem as well.

**Comment by and-reas-se** [comment]
@davboecki if you find that useful you might also be interested to know that another workaround for that bug is if you configure the sidedness of gtce machines so you can't insert on the output side (which is the default, but not what you'd do when using just a crafting module), put the crafting module on that output side, and insert the ingredients on another side via a sattelite pipe.

Also, LP seems unable to pull items from the output slot if you don't put the chassi on the output side, but other mods (for example enderio conduits) can do this.

Definetly seems like something is going on with sidedness and which slots are accessible.

**Comment by Rectorian** [comment]
After some more testing, I believe it was because the auto-output was facing towards my chassis pipe and because the pipes check inventories slightly slower than the auto-output on the EBF, it would spit them into the system and the system wouldn't recognize that is a requested item and just sent it to the default route. To add more to this, I think crafting times might not be needed but could be useful statistical information for the crafting monitor upgrade to see how long it might be until a given recipe finishes.

**Comment by and-reas-se** [comment]
@Rectorian yeah if you want to use a crafting pipe/module you should not turn on the auto output feature, you need to let the pipe pull the item out.

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
