### ISSUE TITLE
Connection indicator on the wrong side

### ISSUE THREAD

**Issue by Tyniann** [RS485/LogisticsPipes#1366]
See screenshot for clarification.

I have 2 autocrafting benches and a crafting pipe inbetween. The pipe has a red + orange dot on the left and a red dot on the right, indicating, that it is connected to the table on the left.
The left table contains the recipe for a blank module, the right contains the recipe for unrouted transport pipes. If I import the recipe into the crafting pipe it pulls the unrouted transport pipe-recipe from the right table (the one with the single red dot) and not the left one.

You can work around this by installing a disconnection upgrade.

Still: Am I misinterpreting something or is this a bug?
Edit: Logistics Pipes Version 0.10.2.203
![2019-08-28_23 19 59](https://user-images.githubusercontent.com/13117389/63893655-0a5ee700-c9eb-11e9-97fa-31000a820101.png)

**Comment by Tyniann** [comment]
Realized that this setup is stupid anyway because it's not a good idea to have one pipe connect to multiple sides.
Haven't played with LP in a long while. ^^
So this bug isn't really relevant anyways I guess.

**Comment by davboecki** [comment]
Well, the problem here is, that all basic pipes are not designed to be used with multiple connections. 
The orange dot only indicates that this is the table the pipe expects to pull out of. BUT that is NOT the place where all sinked items will go and is not the pipe the import help button will use. Especially the part where items will be inserted into both tables at random will mess up everything anyway, so I don't see a reason to change anything here.
