### ISSUE TITLE
Please tag releases.

### ISSUE THREAD

**Issue by Turmfalke2** [RS485/LogisticsPipes#1374]
hi,
Apparently you stopped doing and release here and only do them on curseforge. Fine. However it is now impossible to figgure out whether a specific commit is a specific version from curseforge. 

The releases on curseforge also have no changelog.

**Comment by Bernasss12** [comment]
I may be wrong but I'm pretty sure the Jenkins builds have a change log so you could use that

**Comment by Turmfalke2** [comment]
http://ci.thezorro266.com is down for me.

E: apparently jenkins moved to https://ci.rs485.network

**Comment by Bernasss12** [comment]
That would be correct, the edit I mean

**Comment by bziemons** [comment]
That url was changed quite a while ago (and changed in READMEs etc.) ;) Releases on GitHub are merely tags and tbh, I'd rather disable that releases tab on here altogether, because we have no intention to add a git tag for **every** build. Sadly it is not possible to hide it, so everyone has to live with it.
