### ISSUE TITLE
[Suggestion] Possible duplicate Logic with Pipes vs Modules

### ISSUE THREAD

**Issue by thatsIch** [RS485/LogisticsPipes#14]
Provider Pipe vs Provider Module for example

Intuitivly there should be only the provider module or is it still in there cause of compability issues?

**Comment by AartBluestoke** [comment]
modules used to be second class citizens compared to full pipes (as they don't need to do allot of stuff), but over time i think they have become closer. Also, providers and crafters are a bit redundant; providers are just crafters with a priority of -1 that need nothing delivered, has the number of things they can send fixed by their inventory, not what others can provide.

**Comment by ArtForz** [comment]
Provider pipe has to deal with inventories on all sides, modules don't.
