### ISSUE TITLE
LP 0.10.2.216 + YABBA 1.1.2.53 + QuickSort Crash

### ISSUE THREAD

**Issue by Nius** [RS485/LogisticsPipes#1413]
Attempting to use a QuickSort module mounted on a MK1 Chassis to extract items from a YABBA barrel containing more than one stack of the target item results in an unrecoverable crash.

The barrel had no upgrades, contained cobblestone, and was the only inventory adjacent to the chassis pipe. The orientation of the pipe did not matter. The cobblestone did have a valid destination, which was a different cobblestone barrel several blocks away connected to a single basic logistics pipe which had a cobblestone in its filter and the default route set to false.

A simple extraction module mounted on the same chassis functioned as expected. Using the QSM to pull from a diamond chest instead of a barrel functioned as expected in an otherwise identical setup (with a barrel as the destination).

The crash was unrecoverable: reloading the server succeeded until it attempted to load the chunk with the offending QuickSort module, which caused the module to tick and repeat the crash. The only solution was to remove the mod, overwrite the block containing the chassis, and then reinstate the mod. This was inconvenient because doing this removed all existing LP blocks, vaporized all LP items in any inventory, and replaced all LP pipes currently in the world with non-functioning, non-connecting broken LP entities.

LP version 0.10.2.216 with YABBA version 1.1.2.53 in modpack FTB Ultimate Reloaded.
The server log containing the crash is attached.
[latest.log](https://github.com/RS485/LogisticsPipes/files/4143501/latest.log)

**Comment by belathus** [comment]
I've had a similar crash: https://gist.github.com/belathus/37757d3507538af1841b8d5ad08581fc

I'm mostly using nether chests and obsidian chests, though. I have quicksort modules on the same mk2 chassis as a provider module, which are being fed by a mk3 chassis with the same modules and an itemsink module set to be the default route.

I was able to  recover the world by setting the "removeErroringTileEntities" line in the forge.cfg file to true.

Edit: the issue seems to exist solely with the nether chests. None of the obsidian chests cause a crash with the quicksort module.

**Comment by Nius** [comment]
Thanks, I wasn't aware of that line item being available in config. That'll
be super helpful.

-- Nicholas P. Harrell

Nicholas.P.Harrell@gmail.com
443-975-6901 or 240-670-6487

**Comment by belathus** [comment]
Make sure you don't leave that line true. Otherwise, you won't get a crash when things go wrong. It'll just delete stuff. But it is super useful for saving a world that was otherwise crashtastic.

**Comment by bziemons** [comment]
Fixed in 86015c19e41781cd92c80b0a5b72946ca344a450
