### ISSUE TITLE
Active Supplier modules customization

### ISSUE THREAD

**Issue by pitris90** [RS485/LogisticsPipes#1452]
Hi, 
I would like to suggest some kind of performance enhancement for active supplier module... We just could set timer in which active supplier module controls items in chest.. I would appreciate longer delays between checking instead of constant checking.

**Comment by bziemons** [comment]
Please check that there are no action speed upgrades applied and see that the attached inventory is not big and not laggy to look-up items on.

**Comment by pitris90** [comment]
There are no action speed upgrades and storage is classic diamond chest, so i don't think its somehow too big

**Comment by bziemons** [comment]
You could try to attach a smaller inventory and see if that helps.

If you haven't, it does make sense to set the supplier mode to Bulk50 so that it only requests when less than 50% of the required items are left.

The lookups of the attached inventory usually dont harm performance that much, except if there is a bug. Please attach versions of MC, Forge and LP as well.

**Comment by pitris90** [comment]
Well it isn't big problem, however i'm running my custom modpack server and a lot of smaller problems can become into big problem. 
MC 1.12.2
Forge 14.23.5.2854
LP 0.10.3.5

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
