### ISSUE TITLE
Logistics Pipes do not power IC2 device

### ISSUE THREAD

**Issue by yves-chevallier** [RS485/LogisticsPipes#1461]
I have made a small experiment illustrated below:

![image](https://user-images.githubusercontent.com/52489316/82554446-39fbe380-9b66-11ea-8ac6-e955eeef9205.png)

All logistics pipes have been upgraded to the `Power Transportation Upgrade` and the one connected to the BatBox is upgraded with the `EU LV Power Supplier Upgrade`. The first time I connect this latter upgrade, I briefly see a spark on the network which disappears in a glance.

I am using Logistics Pipes 0.10.3.14 on Minecraft 1.12.2 with IC2 mod installed.

Is there bug or do I have missed something?

**Comment by bziemons** [comment]
The power transportation does currently not work with LP on MC 1.12 - thats why the blocks and upgrades do not have a crafting recipe nor can they be unlocked. Re-adding the feature wasn't done, because actually having a version for MC 1.12 was a priority. I will put this in as a feature request - currently I am not sure when power transportation will be back

**Comment by yves-chevallier** [comment]
Is this issue valid with all kind of power transportation? Is this due to a conflict with other mods or because things changed too much between MC <1.12 and MC 1.12?

**Comment by bziemons** [comment]
The problem is the integration to other mods. Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
