### ISSUE TITLE
Forward this mod

### ISSUE THREAD

**Issue by wstc1997** [RS485/LogisticsPipes#1501]
Dear author, I want to repost this mod you developed to the Minecraft China Forum（https://www.mcbbs.net）, I hope you can agree to my request.

**Comment by bziemons** [comment]
Yeah, don't hesitate to. The license explicitly allows redistribution. I have no idea what the current situation in China is and I don't know if you can access our Jenkins for builds. Additionally it would be nice to have information about the mod's fingerprint so that people are able to check that the mod Jar file was not compromised or modified.

**Comment by wstc1997** [comment]
Okay, thank you very much. I can currently access Jenkins in China, and I will explain all relevant information in my post, including mod's fingerprint.

**Comment by wstc1997** [comment]
> 是的，不要犹豫。该许可证明确允许重新分发。我不知道中国目前的情况如何，我不知道您是否可以访问我们的詹金斯大厦。此外，最好拥有有关mod指纹的信息，以便人们能够检查mod jar文件是否未受到破坏或修改。

Can I provide a download channel directly on the MC China website to make it easier for MC players in China to download this mod. Because in some areas of China, players can’t log in to Curse Forge, and they don’t know how to download from Git Hub.

**Comment by wstc1997** [comment]
> 是的，不要犹豫。该许可证明确允许重新分发。我不知道中国目前的情况如何，我不知道您是否可以访问我们的詹金斯大厦。此外，最好拥有有关mod指纹的信息，以便人们能够检查mod jar文件是否未受到破坏或修改。

Can I provide a download channel directly on the MC China website（https://www.mcmod.cn/）? This will make it easier for MC players in China to download this mod. Because in some areas of China, players can’t log in to Curse Forge, and they don’t know how to download from Git Hub.
