### ISSUE TITLE
Timeout on Async Module - Server Error

### ISSUE THREAD

**Issue by ghost** [RS485/LogisticsPipes#1536]
The specific error listed is:
[Warn] [logisticspipes]: Timeout on async module DeferredCoroutine{Active}@7823a7a9

The string at the end after the '@' changes every 10 seconds or so, and I'm not entirely sure what's causing the error.

**Comment by cypren** [comment]
I'm seeing this error on my server as well, along with very poor LP performance (extractor module with 16 speed upgrades is only pulling items once every 40-60 seconds or so). We're barely using the mod at the moment; there are fewer than half a dozen existing networks with less than a dozen nodes each.

Edit: because I'm an idiot, I didn't include the most important information the first time around: this is on LP 0.10.3.50 with the All The Mods 3 Expert pack version 1.9.0.

**Comment by bziemons** [comment]
> I'm seeing this error on my server as well, along with very poor LP performance (extractor module with 16 speed upgrades is only pulling items once every 40-60 seconds or so)

The actual extraction rate depends on the performance of accessing the attached inventory. The timeout was meant to identify performance problems, but those didn't occur in testing. I have increased the timeout anyway, because building our routing table also counts towards this. If it still occurs with the newest build, it should contain debug info and a stack trace. So if you still see this in your log, please open a new issue and I'll have a look then.

**Comment by bziemons** [comment]
I have found two other problems which I fixed in de401cb281384328c34c8e1fe890f0a88529ee55. The first was the advanced extractor not correctly working and the other fixing a problem that seems to be occurring since a Kotlin standard library update and basically was wrong usage of their API. Please retest if still relevant to anyone and open a new issue when there is still a problem.
