### ISSUE TITLE
[req] config option for remote orderer

### ISSUE THREAD

**Issue by NoX-programer** [RS485/LogisticsPipes#154]
There is real need to have some option like PowerUsageRemotePer1km (better to make it fractional number).
<offtop> Players on our vanilla server without region protection lives at 300k (and more) far from each other. Very often there is need to request something to ender chest, but can not since last update to v0.7.3.dev.640. </offtop>

**Comment by AartBluestoke** [comment]
use a logistics inventory system connector via ender chests to bridge the distance. 
The Logistics Item Card to connect them can be made at the soldering station.

**Comment by AartBluestoke** [comment]
a remote requester connected to the pipe on the left pulls from the network on the right.
![image](https://f.cloud.github.com/assets/1892829/942412/54fe7b58-01ac-11e3-80a2-059b07d1f8d5.png)

**Comment by nf404** [comment]
this is uncomfortable to switch between bridged remote orderer pipes

**Comment by NoX-programer** [comment]
I know how to connect distant parts of LP-networks but how to be in case when I visiting a distant player and want to "stay online" with my LP-system (remote orderer+ender pouch)? I see the solutions:
- build on each player's base my enderchest+logistics inventory system connector+remote orderer log. pipe and
  -> have a stack of unstackable remote orderers
  -> re-link 1 remore orderer each time when visiting another player
- disable the power usage trough LogisticsPipes completely by setting B:powerUsageDisabled=true because even I:powerUsageMultiplyer=0 didn't make remote orderer to work

So sad, so pity solutions... Meanwhile I using the second one (B:powerUsageDisabled=true). No good, so no good...

**Comment by AartBluestoke** [comment]
1) - you only need to carry a chest, an ICS pipe, 1 card and the request pipe with you, you can pick up and move it when you travel; 

2) the distance cost is now decreased so that a full power node can work to 2000km. (edit: i originally wrote 1000, but the patch actually makes it 2000)
(i recommend putting in more than one power node if you're going to be doing much traveling, if one is half full, and can't service a request, others will be used automatically)

edit: 
also, feel free to re-open this if you feel the cost is still to excessive ...
