### ISSUE TITLE
Satellite List shows a List full of the same entry on Dedicated  Server

### ISSUE THREAD

**Issue by SonOfTheStars** [RS485/LogisticsPipes#1586]
On our FTB Interactions Dedicated Server, we pretty much daily face the issue that satellite pipes of all sorts show up in the list of available satellistes as a single entry.

E.g.: We have a Satellite named "Cutter". If I open the satellite selector list in any place (Crafting Module, Crafting Pipe or Crafting Manager from LogisticsBridge), the list shows all slots of the list filled with just "Cutter". 

This happens especially after a new satellite is added to the network and when a satellite is broken.

Mode: Dedicated Server
Forge Version: 14.23.5.2847
LP Version: 0.10.3.94 Alpha

**Comment by bziemons** [comment]
Isn't this basically the same as #1585 ?

**Comment by bziemons** [comment]
Wontfix today since this is related to caching by the following:
https://github.com/tom5454/LogisticsBridge/blob/c69deecf6e85512391886ff9d2d0cc54c4ffc23c/src/main/java/com/tom/logisticsbridge/pipe/CraftingManager.java#L66

Our duplicates would actually be removed, if the garbage collector sees them as un-referenced pipes, but the pipes are kept against their will in Logistics Bridge.

**Comment by SonOfTheStars** [comment]
Wow I am stunned that I didn't find this myself! Great job figuring this out! I'll see to getting that fixed immediately!
