### ISSUE TITLE
OreDict Itemsink loses configuration on UI close

### ISSUE THREAD

**Issue by SonOfTheStars** [RS485/LogisticsPipes#1609]
As title says.

LP version: 0.10.3.114

**Comment by v1993** [comment]
Can confirm that this happens, renders oredict sink completely useless.

**Comment by logoster** [comment]
i'd also like to confirm that this is still happening, and as v1993 says, it renders the oredict item sink module completley useless

**Comment by AngryCarrot789** [comment]
Could it be due to the fact that, during the constructor of GuiOreDictItemSink, it copies the module's oreList field, instead of storing the oreList as a field in GuiOreDictItemSink? (it copied the oreList into a new list called guiLocalOreList, which should be changed to instead refence the module's oreList)

**Comment by bziemons** [comment]
> Could it be due to the fact that, during the constructor of GuiOreDictItemSink, it copies the module's oreList field, instead of storing the oreList as a field in GuiOreDictItemSink?

The change needs to be send to the server, so it shouldn't really matter if it copies the list or uses the module's oreList field. It seems like the changes are not sent to the server right now. Also it seems like I simply forgot to fix this code

https://github.com/RS485/LogisticsPipes/blob/1e662790e7fe78c312cb074badae639b585cda40/common/logisticspipes/gui/modules/GuiOreDictItemSink.java#L26
