### ISSUE TITLE
Logistics Request Table / Crafting Pipe should use OreDictionary when requesting items.

### ISSUE THREAD

**Issue by russjr08** [RS485/LogisticsPipes#176]
Currently the Request Table tries to request _exact_ copies of an item. However when for example, pasting in a recipe from NEI, the type of ingot or such might not be the type you have in your system. It should try to request a different type, if the one in the recipe isn't present in the system.

Edit: Forgot the Crafting Pipe doesn't support this either. Added as per MrVoltz suggestion :)

**Comment by MrVoltz** [comment]
This should have Crafting pipes, too.

**Comment by MrVoltz** [comment]
And logistics crafting table too :D

**Comment by Unknown-Zombie** [comment]
I would love for this to happen; I came here to suggest the same thing.

Or at least if the Request Table could accept the Fuzzy Crafting Upgrade.

**Comment by Garagoth** [comment]
Or OreDict upgrade, because sometimes you really want to make exact recipe with exact item (eg. wood type) in a LCT.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/pull/363

**Comment by Unknown-Zombie** [comment]
I don't understand why this was closed. The Logistics Request Table still doesn't utilize the OreDict.

A new crafting table was added, which I don't really understand the usefulness of because doesn't it just replace the functionality of the Fuzzy Crafting Upgrade?

**Comment by cybcaoyibo** [comment]
suppose you have a crafting pipe that is configured to craft one chest with 8 oak planks, and your provider can provide 8 birch planks.
if your pipe doesn't have fuzzy upgrade, the request will fail and birch planks won't go to crafting table.
if your crafting table isn't fuzzy, the table won't actually do the craft even if 8 birch planks have arrived.

but yes, request table still doesn't have a fuzzy one

**Comment by bziemons** [comment]
Reopened because of the Logistics Request Table.

**Comment by MikeLydeamore** [comment]
Any news on this? I've noticed the Logistics Request Table now has a slot that takes a Fuzzy Crafting Card, but it doesn't seem to be functional yet?

**Comment by mikeloeven** [comment]
To be honest there should not be any upgrades the ability for tables and crafting pipes to use the oredict should be built in. the simple fact is that in large packs such as ftb you have sometimes 5-6 types of ingots for a single material and little control of which one your machines produce as for example a macerator makes ic2 dusts which cook into ic2 ingots unless of course you put them in a smelter than you get TK etc etc. Crafting pipes should not be as picky as they are and should not require any special upgrades lets face it copper is copper tin is tin bronze is bronze. the crafting pipes should use oredict by default because thats why it's there and this issue is making crafting in a large system a hell of alot more complicated than it has any right to be FFS and frankly i am sick and tired of having to sit in front of my storage system for hours with a forge lexicon manually converting shit.

**Comment by 1n5aN1aC** [comment]
@mikeloeven I agree with you, however.....

I'm not sure how this can be implemented in a way that won't break, at least when it comes to crafting tables.

If the oreDictionary was limited to just ores and ingots, it would be amazing, but what about other uses for the ore dictionary, where the items appear in the dictionary, but are not the same (dyes, perhaps?) and therefore don't work interchangeably in recipes.  ....and we can't just check the recipe, because the crafting machine could be any number of complex contraptions that we can't read what the recipe IS.

But I am for an overhaul in ore-dictionary compatibility GUI and/or inclusion of that functionality by default.

**Comment by mikeloeven** [comment]
Actually it already is with the oredict option in fuzzy upgrades i am simply arguing that this should not require a upgrade but rather be a default function of the pipes

**Comment by bziemons** [comment]
Added to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests *Logistics Request Table Improvements*
