### ISSUE TITLE
placement rules upgrade for crafting pipe

### ISSUE THREAD

**Issue by loordgek** [RS485/LogisticsPipes#193]
it would be really nice to have the placement rules upgrade for crafting pipe

**Comment by JustinMcDonald** [comment]
+1

**Comment by bziemons** [comment]
I would rather deny this, because when you think about a machine that needs this, it is mostly machines that should not be used with autocrafting. This addition would break balance in probably over 50% of the times where you need it.

**Comment by loordgek** [comment]
can you give a example where it can be op

**Comment by AartBluestoke** [comment]
the main thing i can think of that would need this is crafting-table-like objects - eg: the QED where you need to put specific things in specific slots...
atm you can't automate a QED with LP, cause you can't build the correct recipe in place.

Perhaps a compromise - an "in-place" inserter, so that things in the first/nth slot of the recipe list go to the first/nth inventory slot of the machine.

re: breaking things:
several other mods already allow targeted insertion, so if there is a balance concern, just include a config flag to disable it, as if you are using a standard (FTB based) modpack, you'll be able to do so anyway.

**Comment by codewarrior0** [comment]
+1 for automating QED with LP.

Would love if the Crafting Pipe would recognize the QED and import its recipes the same way it does with the Railcraft Rolling Machine.

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
