### ISSUE TITLE
OreDict item sink improvements.

### ISSUE THREAD

**Issue by ruifung** [RS485/LogisticsPipes#231]
I suggest the OreDict itemsink module allow for manual entry of the oredict entry, this allows for setting it without having the requisite item available. Also is it possible to allow it to use wildcard matching? like ore\* will match all OreDict entries which start with ore.

**Comment by AEnterprise** [comment]
i don't know about that wildcart but i think that oredictionary support would be great

**Comment by bziemons** [comment]
The suggestion is to have an extra text field on the OreDict Item Sink module. Just to bring this back up.

**Comment by Xuerian** [comment]
As this is the most relevant to my uses of the four? oredict tickets and they're all labeled Needs Comments..

Being able to type each OreDict ItemSink entry by hand (and ideally use wildcards) if desired would be very helpful.

A simple text field and [+] button above or below the item slot&candidate list of the OreDict GUI would be adequate for input.

**Comment by bziemons** [comment]
Other than the ideas in here, a new one has come up in issue #649 from @Xuerian:
"The ability to use partial names would really be helpful when you add the second thing, however judging by your opinion of the first, it may warrant an upgraded module."

I agree by having an upgraded version which has a text field and can use wildcard matching with an asterisk. Maybe even have another upgrade for wildcards?

**Comment by hron84** [comment]
I absolute agree w/ 3 tier oredic module if the text field is the second :smile:

**Comment by davboecki** [comment]
I think the best would be to add a second tier with a textfield which supports wildcards.

**Comment by Xuerian** [comment]
To be frank, Ore Dictionary is just in a really bad state in larger packs.

Forge doesn't pick one material and ignore the rest (Like they are with liquids, now), instead we have four copper ores/ingots/blocks/nuggets/dusts that all act the same, craft the same, but have to be treated specially and we have to use upgrades to deal with, and good luck if your machines give you different types - or if they don't give you the first alphabetical one. 

If I was going to put the work in or was doing it myself, basic oredict functionality (For single items/oredicts) would be universal and not an upgrade. Dealing with multiple mod versions of the same item really shouldn't be considered a challenge. It's tedium due to bad design. 

But, this is just my opinion on it, I'm not doing it myself, and the more or less normal behavior is "Oredict functionality is an upgrade" in most pipe or item handling mods, so.. *Shrug*


Looking forward to the wildcard upgrade though. Thanks.

**Comment by hron84** [comment]
@Xuerian thanks for your opinion. We have to differentiate OreDict handling in pipes and in machine/crafting recipes. While recipes _should_ support ore dictionary entries, pipes aren't neccessarily. Think to early game item sorting, you just want to sort your items into barrels/drawers/chests, nothing more. It is not requires ore dictionary item handling anyway. After you start building a bit bigger factory (for example with Pulverizer/SAG Mill and some furnace-like machine) you will get nearly same ingots, so in sorting you still not need an ore dictionary handling, just for processing. It means 3 or 4 OreDict-related pipe or upgrade and still does not requires the whole system to support Ore Dictionary.

I think it is partially a performance decision. You can route a single ItemStack more easier than scanning all Ore Dictionary entries for that item. It is not too much if you route a single item but if a lot of item pass through your system, you will get better performance if you do not scan OreDict for every single item.

**Comment by hron84** [comment]
A slightly related idea: Polymorphic upgrade should get an OreDic upgrade and advertise all oredict entries where it is possible. It would be good since we have storage stuffs like JABBA that can convert between OreDict entries automagically.

**Comment by bziemons** [comment]
Let me just link to https://github.com/RS485/LogisticsPipes/issues/381#issuecomment-59911794
And also add that the ore dictionary is in some mods used as a category of items and not only describing the same item in different mods.

And @hron84 as a module the polymorphic item sink cannot really have an upgrade.

**Comment by Xuerian** [comment]
Instead of derailing this into an entire discussion about the use/misuse of the ore dictionary, I removed that rant. I appreciate your work on more modules.

**Comment by hron84** [comment]
@theZorro266 I'm OK if this kind of support is more specific, I mean especially ingots, dusts and ores. These stuffs are used "correctly" in most mods I know. However, I always have a problem with my barrel system since I have some type of item, but as I get better and better tech to process ores sometimes the yield of processing changes suddenly without any notification. For example. I playing w/ Flux Galaxy with some mates on a server and we upgraded our ore processing to mekanism system but Mek does not yield Forestry ingots (that we already programmed in our LP system) but yield a Mek ingots, and all processed ore landed in the default route (a buffer chest). I think this is quite far from optimal.

I accept there is a lot of things have to be done with OreDict support, I do not expect an ASAP solution, especially because I can live these limitations. However, I would appreciate some solution for these kind of problems. Any update, any change in the modlist can change the type of yields (if they're equal), so we can't really rely on one specific item type in these cases.

Upgrade: I used wrong words I mean something like Advanced Extraction Module Mk[12]

**Comment by bziemons** [comment]
Of course something has to change. I am currently thinking about Ore Dictionary support. I just do not have enough spare time to really program in LP right now. I will try to start with the Request Table though and I already started thinking about things to change. When I have a concept, I will make a new issue about it.

Regarding this issue: We have accepted it and it will be implemented as davboecki said https://github.com/RS485/LogisticsPipes/issues/231#issuecomment-92106710
As well as in other tickets, I would like to keep this on topic. In fact #381 should be the ticket where you can bring up any solution and ideas to the Ore Dictionary support in Logistics Pipes and where general discussion about the Ore Dictionary support should happen then.

**Comment by hron84** [comment]
@theZorro266  thanks for pointers and sorry if i were offtopic

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
