### ISSUE TITLE
We do some weird stuff with special inventory handlers.

### ISSUE THREAD

**Issue by GUIpsp** [RS485/LogisticsPipes#274]
Even if a special inv handler exists, we still use the generic one sometimes.

**Comment by davboecki** [comment]
Could you point out the places where wo don't use the special inventory handler.

**Comment by GUIpsp** [comment]
I've completely forgotten about this issue, but there was a problem with JABBA barrels. Don't exactly recall what it was, or if it was fixed our not. Better ask ProfMobius.

**Comment by bziemons** [comment]
We're using JABBA on 1.7.10 right now. There does not seem to be a problem. I assume it was fixed?

**Comment by GUIpsp** [comment]
Mobius implemented a workaround. We were causing a lot of lag, and I couldn't pinpoint where exactly we were not using the special handler.

**Comment by AartBluestoke** [comment]
guipsp (or anyone else), feel free to throw a jvisualvm sampled .nps file (maximum sampling rate, atleast 30 seconds worth of recording while the issue is being caused) at me if you ever feel that LP is causing lag, i try to fix things that run slowly.

also, this issue may have been caused by a bug with JABBA whereby reading the contents of a barrel was causing a block update, even though nothing was being changed.

**Comment by GUIpsp** [comment]
Stacktraces showed that we were using the default inv handler IIRC

**Comment by davboecki** [comment]
Do you mean like this: https://dl.dropboxusercontent.com/u/33855125/LogisticsPipes/profile_1.png ?
Because we create that accessmap BEFORE we wrap the inv if they have a special handler. So in the case in the pic it will still use the special inventory handler for Jabba.

**Comment by GUIpsp** [comment]
Nah, was calling a codepath that is used for non-special invs in jabba. Again, not sure if it has been fixed or not.
