### ISSUE TITLE
[Issue]AE Interface + Provider/Request pipe combo

### ISSUE THREAD

**Issue by JerkJerky** [RS485/LogisticsPipes#276]
So i found HUGE performance issue, cause ae bug tracker is off (AE2) i upload it here:
![before](https://f.cloud.github.com/assets/4322367/2285175/cb316af6-9fd1-11e3-9e89-ca1d47265524.png)
^ My world tps before i place request pipe
![inbetween](https://f.cloud.github.com/assets/4322367/2285174/cb1b2228-9fd1-11e3-9939-fd203b8c7930.png)
^ Difference of tps value's 
![after](https://f.cloud.github.com/assets/4322367/2285176/cb3c06be-9fd1-11e3-88e3-d08bd948a806.png)
^ TPS then i placed request pipe
![and peace again](https://f.cloud.github.com/assets/4322367/2285177/cb3f887a-9fd1-11e3-8653-a04c63db9319.png)
^ TPS after destroying requester

Maybe that one of the mods make infinite loop "feeding" eachother with data. I don't know.
And yea i have a lot things in my AE system.

**Comment by dewdkorn6969** [comment]
ive seen that 2.. i fixed it by putting a firewall pipe down configured to block the provider pipe from providing to the request pipe.. be sure to allow all the other stuff just block it from providing to the request pipe.. ive only seen it lag like that when i have a configured interface tho.. once i broke the interfaces the tps lag goes away

**Comment by davboecki** [comment]
That's probably an AE bug, because LP only checks the provider pipes, when there is a request for that, or a supplyer pipe, but even then LP only looks up the storage of AE, and not the crafting. AE considers LP a "crafting" request so LP doesn't even ask for the items inside any LP system. So it's likely that this is an bug inside AE. (If it even is a "bug", could also be the only way to handle the interaction, I can't tell you that)

**Comment by ruifung** [comment]
@dewdkorn6969 How do you block the provider from providing to the request pipe, without blocking other providers elsewhere on the network from providing to it?

**Comment by AEnterprise** [comment]
use a firewall pipe

**Comment by dewdkorn6969** [comment]
@ruifung you have to lay out your pipes in a way that will allow the provider pipe to get through to the rest of the network but have the firewall pipe next to the request pipe... i.e. on the test setup he did above it wouldnt work since he has nowhere to put the firewall pipe to do that he has to spread the pipes out more to block it without blocking the provider from getting to the remote requester pipe..

another issue ive seen is if you have multiple provider pipes on interfaces the amounts shown in the request pipe counts every item in the ae system twice or more times so you also have to block multiple providers on the same ae system from getting to the same request pipe.

ive basically given up on using ae for any sort of requesting or crafting.. i just have a request pipe attached to a me chest as an input into the system and ae is just a huge storage system to me with the me crafting terminal being used to craft using that stuff inside the ae system and lp handling all the crafting outside through the request pipe...

**Comment by ruifung** [comment]
LOL, Personally I just use AE as some kind of back end storage, with a provider and sink on it.
