### ISSUE TITLE
Name based sink module

### ISSUE THREAD

**Issue by MrTJP** [RS485/LogisticsPipes#29]
Im just going to leave this here, since it was a past issue...

http://oi45.tinypic.com/2sb33me.jpg

Obviously very primitive, but its almost done...

**Comment by AartBluestoke** [comment]
the problem with a name based sink, is that the server doesn't have a language, so there isn't a human readable name which the server knows about, other than the class of the item. The current solution with CC involves a client manually sending their language data to the server, so that a match can be made server side.

hmm, could we have a select language button .. find "ore" in 'en'. - because the server can fetch a language specific name for something.

building and inserting a dictionary-letter tree (with string/itemID leaves) wouldn't be that hard ...

**Comment by MrTJP** [comment]
For this to work ive used the same method the cc command in the core routed pipe. Ive tested in single player and it does work. Im not sure about a dedicated server though.

**Comment by davboecki** [comment]
SSP uses the real item name function. On the dedicated server /lp tn is used so different names are possible.

**Comment by MrTJP** [comment]
I see. So simply using getfriendlynamecc wont work?

**Comment by davboecki** [comment]
It works but not correctly. So in SMP it can cause some weird behavior. The /lp tn language database is more or less only a workaround.

**Comment by MrTJP** [comment]
Can i get some basic info on how to handle this?

**Comment by davboecki** [comment]
How to handle what?

**Comment by MrTJP** [comment]
i never mind.  i think i will just finish the module with how it is and it should be quite simple for you do change is to the correct way...

**Comment by AartBluestoke** [comment]
feel free to join irc - #rs485 on irc.esper.net is where davboecki,artForz and I are on, most of the time.

**Comment by MrTJP** [comment]
https://github.com/MrTJP/LogisticsPipes-Dev/commits/Dev

**Comment by ghost** [comment]
What happened to your fork? Did you submit a PR?

**Comment by GUIpsp** [comment]
@sadris A pr got submitted, but it didn't get merged quick enough AFAIK

**Comment by bziemons** [comment]
@GUIpsp No, it just was not finished enough to merge it

See https://github.com/RS485/LogisticsPipes-Dev/pull/31
