### ISSUE TITLE
Provider pipe with GT Digital Chests.

### ISSUE THREAD

**Issue by MyEternity** [RS485/LogisticsPipes#326]
Provides only stack from chest, but it contains, for example 20+k of dirt.

**Comment by bziemons** [comment]
If APIs would be APIs this wouldn't be a problem. I think there was an integration.
I would not suggest implementing support for something that does change as fast and where there is no-one able to update our integration constantly.

**Comment by bziemons** [comment]
We have decided to remove compatibility with GregTech, as there are many other mods that we are already compatible with. We try to hold on common implementations like the DSU API, but there is no note about that in GregTech and Digital Chests.

https://github.com/RS485/LogisticsPipes/commit/614fb15df2197a7791f3bf29a34d82d77a3003b5

**Comment by hron84** [comment]
@theZorro266 Is there any way to connect with GT devs to figure out some solution? Even if I accept your decision about removing GT compatibility, I think stopping a support is not a good thing for the community - at least for those who love both mods (GT and LP). And GT is a typical example where LP can help a lot for automating very difficult craftings. Even if I know AE2 still has some integration with GT, LP one would be very kind.

**Comment by bziemons** [comment]
Stopping support for deprecated (and in this case not working) APIs is a good thing. The way to make GregTech's Digital Chest compatible again is in my comment above, but I guess GregTech users have to ask for that.

**Comment by PaladinOne** [comment]
The Digital Chest isn't actually a thing anymore. It was never re-added into GregTech 5, and Greg is currently working on development of GT6.

Also, "provides only a stack" was the intended behavior of the Digital Chest. It could store enormous numbers of items, but would not expose more than a single stack of them at a time.

**Comment by hron84** [comment]
@theZorro266 <del>Stopping supporting deprecated/non-working things is a very good thing however, if it directly means we stop supporting a mod completely... that's a different thing. I can understand both sides, since users can ask an enormous numbers of things and most developers have no time to check every single request and answer it. I really honor you at LP team since you answer nearly all request but I can imagine Greg just miss these words especially because he tries to maintain his mod in a single forum thread... ehh.</del>

**Edit**: I just read Greg's reply and re-read the mentioned commit. I never used GT's Digital Chest since I used different things to store my GT items (LP/JABBA or AE).

**Comment by bziemons** [comment]
@hron84 I see.. I said "remove compatibility with GregTech", which sounds like we are incompatible with GregTech now, but that is not true. The DigitalChest was the only thing we actually supported actively in GregTech (from our code), so I basically removed all of that support. Just to put this right.

**Comment by hron84** [comment]
That's why I re-edited my comment, but since GH sent it you as an e-mail, I would not like to change the past so i just striked it over.
