### ISSUE TITLE
re add the builder supplier pipe

### ISSUE THREAD

**Issue by loordgek** [RS485/LogisticsPipes#435]
see title

**Comment by bschoenmaeckers** [comment]
this would be great.
where is the like button...

**Comment by TheLoneWolfling** [comment]
This would make builders much more useful. +1.

**Comment by bziemons** [comment]
I mean sure, if someone wants to make it.. go ahead ;)

**Comment by FirzenDark** [comment]
I was searching on the internet and came across a Builder Supplier Logistics Pipe, but it looks like it is not available in Logistics Pipe. 

This will be a wonderful pipe to have.

**Comment by loordgek** [comment]
hey @asiekierka maybe can you look at this plz
![puss-in-boots-shrek-497126](https://cloud.githubusercontent.com/assets/4789835/10200873/3f5e4b7e-67a9-11e5-8a86-69d818e982d1.jpg)

**Comment by asiekierka** [comment]
Don't ask me - since BC 7.0.2something/7.1.0, we bundle hea3ven's improved request API - now you can just check if a tile is an IRequestProvider, and fulfill its demands as to what stacks it needs!

**Comment by Morketh** [comment]
"Don't ask me - since BC 7.0.2something/7.1.0, we bundle hea3ven's improved request API - now you can just check if a tile is an IRequestProvider, and fulfill its demands as to what stacks it needs!" 

O_e Ive been a python developer for years and that sentence sounded pretty technical but can we have that in plain ole fashion English? i would love to have the build-craft builder supply pipes again. would even try to link ComputerCraft up to make some sort of request Program

**Comment by AEnterprise** [comment]
@Morketh to put it simply: there is an api interface that LP can use to check what the builder is asking for

**Comment by Morketh** [comment]
i understood that much. i guess the real question i was trying to ask was how to interact with said API in order to retrieve items..
namely which pipes do this? (or is this a default of all Logistics Pipes now?)
and then since its an API offered by LP im going to guess that possibly its the builder that doesn't link into it? I could side step the Builder side of the APi all together by giving ComputerCraft a list of items and totals. But how would I link into that "IRequestProvider" ?

"LP can use to check what the builder is asking for"
O_e how exactly does LP run that kind of sanity check? Ive hooked up every LP known to Minecraft and couldn't get any item to automatically pull from my storage i ended up using a request pipe and a wrench and babysitting my builder.

**Comment by AEnterprise** [comment]
@Morketh i think you misonderstood, the api isn't from LP, BC has an api LP can use to see what the builder (and robots) are asking for

**Comment by asiekierka** [comment]
Adding OpenComputers/ComputerCraft support for IRequestProvider is not a bad idea and I will consider it.

**Comment by Morketh** [comment]
I may have misunderstood originally however that cleared up a lot. With the IRequestProvider on the Builder this still kinda brings us back to which pipe can interact with Builder to provide requested Items for the life of me I could not figure it out. is there a logic gate or something i have to use in order to get the items to be requested or is this just an automatic thing?

@asiekierka I think that is a phenomenal idea. I cant wait to try that out.

**Comment by davboecki** [comment]
@Morketh This issue is about adding that support to LogisticsPipes. There is no support for that interface inside LP right now. This is not a changelog it is a feature request.

**Comment by Morketh** [comment]
@davboecki I understand that this is a feature request. i was not looking for a changelog (I can read all the commit history documentation if i wanted that kind of detail) how ever based on other comments in this feature request thread there was implied support that already exsits.

AEnterprise: `i think you misonderstood, the api isn't from LP, BC has an api LP can use to see what the builder (and robots) are asking for`

Unless i miss understood this again that tells me there is an interface currently in place in order to access a list of required items. At the very least this interface exists on the BC side. 

Asiekierka ``since BC 7.0.2something/7.1.0, we bundle hea3ven's improved request API - now you can just check if a tile is an IRequestProvider, and fulfill its demands as to what stacks it needs!`
now if we can clarify exactly what this implies: if i understand this correctly LP can check the tile (Builder) if its an IRequestProvider and report back with item stacks. if that is the case that can be inferred to mean that there is already support included in the currant release of Logistics Pipes to provide Requests?
Half of what im reading says there is support the other half says there is not support BUT there is planned support. O_e all im asking is to clear up the confusion on those key points so the community at large can understand that there is or is not currently any method to supply the Builder with Requested Stacks

**Comment by davboecki** [comment]
What AEnterprise and Asiekierka both are saying is that there is an interface on the BC side that provides easy access to the items required by the builder. Nobody ever sayed that there was support for that interface from LP's side. That's the missing part for the system. LP needs to know how to handle this interface.

**Comment by bziemons** [comment]
@Morketh there was a builder supplier pipe, as the title reveals and the actual work the pipe does is very similar to a supplier pipe, hence the name "builder supplier pipe". So there is no support for anything like a IRequestProvider right now, but it is possible without too much work to create such a pipe. Just to clearly answer that question of yours.
