### ISSUE TITLE
Issue with multiple ore dictionary names for OreDict ItemSink module

### ISSUE THREAD

**Issue by AT611** [RS485/LogisticsPipes#438]
Issue related to GregTech 5 mostly.
Yellow and Brown Limonite dusts, according to GregoriusT's [post](http://forum.industrial-craft.net/index.php?page=Thread&postID=168695#post168695), has multiple ore dictionary names. In OreDict ItemSink module they are both shown as "dye", which is confusing for me and my sorting system.
Can you make oredict name display on top of the module's interface editable with ore dictionary name validation?

**Comment by AT611** [comment]
... or make that field as some sort of drop down list with all oredict names of an item that's being added to the module's list.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/issues/383

**Comment by hohounk** [comment]
Did you notice the fact that it is in fact possible to get the list of all oredict names for an item somehow as NEI is clearly capable of doing it?

**Comment by bziemons** [comment]
Thats not the point. It was not part of the official OreDict API and probably still isnt.

**Comment by AartBluestoke** [comment]
The problem is that most of the work in lp is checking if items are equal
(can craft, have space, want to supply) without an official way to say "is
item a equal to item b" all we can do is either build our own compete copy
of the or dict, and cater for a many to 1 mapping or search the entire dict
to say "what else is this" every time we want "is A=B". I imagine we would
consider a pr for the former, but the large size of the duct would make the
later not so viable.

**Comment by hohounk** [comment]
You do realize that Forge itself registers some vanilla stuff under several oredict labels, right?

**Comment by davboecki** [comment]
Let's review this again, maybe there is some way of doing this.
