### ISSUE TITLE
Configurable accepted power types

### ISSUE THREAD

**Issue by DarklingGX** [RS485/LogisticsPipes#474]
Would you be willing to add a config file to control which power types are accepted? I would like to only allow MJ input, but atm is seems there is no way to configure it as such. If there is, please let me know. In case you are wondering why, I have always been a firm believer in making every mod useful, and currently MJ is rendered obsolete by RF, so I intend to make more machines MJ exclusive, primarily LP. I have disabled the ability for power conduits to convert, but I can't stop LP from accepting RF.

**Comment by bziemons** [comment]
In what case do you have RF and MJ at the same time and only want to filter MJ? It would be perfect, if you had a screenshot attached to your answer.

**Comment by DarklingGX** [comment]
:/ I can't really think of a good way to screenshot that. However, my intentions with disabling RF is quite simply to make MJ more useful. I intend to try and create a modpack at some point that will use several major mods and attempt to make them more difficult that way every mod can be utilized. I respect the time and effort that people put into making mods, and it has always been a huge pet peeve of mine when a mod renders another one useless. Unfortunately, the developers over at Buildcraft have been thrown under the bus as of late, and RF just takes over full force. I miss seeing massive grids of combustion engines or even using things like Forestry's peat engine, and I want to try and bring back its retro style, if only to a few people. What I have personally decided is to use EU, MJ, and RF only on certain machines types in order to create an effect much like utilities in a modern home: you have to run your water over here, you have to run your electrics here, your cable, etc., etc. My intention is to have RF be the major strain for automation and processing (as is the nature of Thermal Expansion with its fancy output side shenanigans), use EU for fancy trinkets n tools like powered drills (I even went as far as to take TConstruct out of my mod path to try and encourage users to explore more with IC2 and the likes), and then use MJ for routing/sorting and things like the quarry of course. AE2 has a config option to take only certain kinds of power to operate off of, so I will use MJ instead of AE power, and I would like to do the same for Logistics pipes. I know it might seem a little trivial to have this presumably annoying to code option for just one guy and his crazy ideas, but I just can't stand when a single mod dominates the play experience, hence the reason that I REFUSE to use the UE mods. I could try and explain a little more in depth should you want me to, but for now I feel this should suffice for reasoning. I apologize in advance if you feel like I'm wasting your time.

**Comment by asiekierka** [comment]
But... why? Forestry is using RF, RailCraft is using RF, BuildCraft is using RF...

@DarklingGX - As of BuildCraft 6.1.2, there is no point in doing that. If you /really/ want to carry on with that, I could make a version of BuildCraft that only outputs to specific mods, but you can't stop TE from doing that.

**Comment by DarklingGX** [comment]
@asiekierka Wait, BC uses RF? I know that TE conduits auto-convert to MJ, but they havent been updated yet. EnderIO does too, but I found a way to stop it. I'll do some more testing to try and see what works and what doesn't, but I would still like to try and push for distinction between the Power Systems. This is an interpretation issue, I know, but I have always seen the challenge with "machinery" in Minecraft (Redstone, Item routing, etc) to be about using very bulky mechanics, and trying to make the best of things and compact them as far as you can. Modding has eliminated some of the strain of this, and that is good, but it has become extremely out of balance, and it needs to change. While this is all well and good, you could say "Just make your own mod!" But this would violate my primary reason in requesting this, and that would be to make every mod imporant. Certain mods are well known for dominating the play experience. Look at Cpt. Sparkles's Ultra Modded Survival series. He had nigh on 200 mods installed, but he only really used 5, the most prominent being Orespawn. I fear that RF is trending towards that, and I don't want to have mods I wont use because of RF being able to do everything that every other power system can. I know that you can say that every mod has slight differences that make one better than another per situation, but lets face it, you are far more likely to throw down a Redstone Furnace from TE than you are an IC2 powered furnace. I have decided to let them keep their territory, but give the others some other uses, like IC2s powered tool set. I want to try and make MJ for routing, but I can't. That is why I want to make them seperate. I want to make each power system useful again.

**Comment by asiekierka** [comment]
@darklingGX - Since BuildCraft 6.1.2 it does. We did it _exactly_ to give an alternative to all the "easy/simple" RF mods, seeing as by the point of the move EVERY. SINGLE. MOD. (bar BuildCraft Additions and QuarryPlus) moved to RF; yes, this includes Forestry (since 3.1, it uses RF) and RailCraft (from 9.4.0.0 on it will use RF).

**Comment by TheOldOne822** [comment]
Player (the IC2 dev) even made an addon so IC2 con use RF. At this point I don't know of any mod that doesn't use RF or its own system with an RF converter.

**Comment by bziemons** [comment]
@DarklingGX First of all, thanks for your reply. There is no wasting time in this, don't worry.
I can understand that you would like to have more depth in your energy network, and yeah, that makes a few things harder. Back to your question, if we make configurable what we accept: I honestly do not think so. You can pull your own version of the source code and edit that in for your mod pack. That is totally fine.
So here is my reason for a no: In modded Minecraft there will always be some unbalance between some mods. Now.. the difficulty with modded MC is something you set by yourself. And by "yourself" I mean basically: every player sets his own difficulty with what he uses and what he does not use.

My goal is not to say: "Here, free diamonds, if you want it easy: use them. Otherwise throw them away."
That is not my point, but there are other things that kindof work like that.. sometimes unintentional, sometimes intentional. I cannot say that Logistics Pipes gives you things for free, so I personally do not think that we need to change anything on balance at this point.

But apart from that there are also technical reasons: RF has a very well built power system (code wise), while BC and IC2.. meh. RF is easy to integrate, has a public API and yeah.. the new BC is using it as well. If there were other well written and unique power systems, we might integrate with them as well. This is not "all about RF". In the end it is also about what people like to use.

So.. much blabla. Here's even more:
Another point that kindof relies to the "set your own difficulty" part: Forcing players to use this specific type of thing by disallowing all the others is poor design. Minecraft is a whole lot about creativity. As well as modded Minecraft is. So if you want creative builts and creative players, don't try to put your players on a specific track, just because you would like it that way. That's not how it works. You can try to bring up rules, reward people with builts that use your rules and let the others be. Because not everybody is equally creative, so blaming people using the easiest possible machine/energy network is not okay.

I guess that's all I had to say ;)

PS: I am so much satisfied and I couldn't agree more with what I wrote here myself, that I have to sign it:
   theZorro266

**Comment by DarklingGX** [comment]
_tips my hat_

That is some good stuff right there sir, I really have no argument left at this point.

However flawed that my plan may have been, I still would like to try and get people to explore mods more in depth though. Would you mind if I asked how you would go about this? I have been thinking a lot about this recently, and I have but a few ideas. The easiest would to be a HQM map, but that isn't a plain survival world, which is partially what I am going for. My other idea was to learn how to make mods, and then create a mod to allow me to add research and progression to majority of the mods, much like Thaumcraft with its glorious research system, but perhaps with multiple branches of research, maybe one scientific and the other magical. I could see that working really well actually now that I think about it. But this isn't exactly the place to go on rambling about this. Just keep being awesome modders. I appreciate all that you have done for the community.

**Comment by bziemons** [comment]
I did mention quite a good system, that might work: Players love to build things. So if you set up something like challenge (maybe every two weeks, depends on the activity of your players, also depends on younger players) that gives your players the opportunity to show their skills. After the time is up you could go through all of them with the players that want to join at a certain date & time.
That also ties the server community a bit. If that works depends on your players and your planning.

Of course there are also other ways of motivating your players to use the whole mod pack.
Making research and progression for one mod alone may be a lot of work, so you should think about that one again.

We can still talk here, if you want. Everyone else can unsubscribe from this thread. Also I am going to close the issue itself, because accepting only one kind of power is not the solution.

**Comment by DarklingGX** [comment]
Hm... That's not a bad idea. It kind of reminds me of the Wrenched map that direwolf20 tried to start. I would have loved for that to go through. I do feel that while the idea is good, it is dodging around why I wanted to do the research idea, and that is for the sake of a more genuine survival experience, one that could be played in single player independent of the community should one chose. Server hosting is a PITA, and can be a little pricey at times, so I would like to try and make this single player friendly. I 100% agree that implementing a research system would be extremely difficult too, but I can't immediately think of another option, not to say that there aren't any.
