### ISSUE TITLE
Crafting Task locking up

### ISSUE THREAD

**Issue by SonOfTheStars** [RS485/LogisticsPipes#493]
Hello,
I noticed a problem with Crafting tasks locking up when there is 1 or more ingredients supplied from a (JABBA)Barrel or Chest, with a Supplier in "Leave 1 per Type" mode. The crafting task seems to both try to pull from the Supplier and issue a subcrafting task for production of that Material
In my case Acacia Wood Planks.

The Item in the Barrel/Chest stays as it should, but the Crafting Pipe (Acacia Wood -> 4 Planks) jams up:
- Emits Purple Sparks indicating a crafting task being waited on
- Igredients(Wood) Have been supplied X-1 (X = Amount)

Manually inserting the Ingredient finishes the Task and un-Jams the Crafting Chain.
Additionally, switching the providers to Normal mode and swopping Poly-Sinks with Standart Sinks fixes it too
Sometimes the Crafting chain finishes but the Plank-Crafter still waits for 1 more iteration

**Comment by charles7926** [comment]
I have also noticed this.  It seems like the queue is not working.  If there are a lot of items coming in to the network from a farm for instance, then any items requested from the logistics crafting pipe will take a long time to create.

**Comment by Intemes** [comment]
I've had this issue using a Crafting Pipe connected to a Thermal Expansion Machine that require a Sneaky Upgrade in the Crafting Pipe. 

Craft Jobs would "sparkle" but the required items would never be pulled.

I've since replaced the "Crafting Pipe+Sneaky Upgrade" with a chest with some additional conduits and filters, and haven't had that problem since.

So without the Sneaky Upgrade in the Crafting pipe everything is working fine.

**Comment by Sidorion** [comment]
I have this issue regardless of the mode the provider module is on.
I have a wall of chests, each with MKII chassis, item sink on default route w. no filters and provider MK I on normal mode.
I set up a crafting pipe and table for pistons and as I demanded eight, the system gave me only three. I looked in the table and saw wood for the remaining five pistons, iron for two more, no cobble and no redstone.
The ingredients for all eight pistons have been removed from the chests (I saw the number decrease in my request pipe) but some of them never reached the crafting pipe.
Another thing: When you quit the game during a crafting process, all items in the tables are lost.

edit: Finally I found all my stuff. I had several crafting tables and -pipes with no recipe set in my system. Those empty tables were between the storage and the tables and the right crafting tables. The items for the crafting went into the crafting tables with no recipes.
So I think, the issue is more, that tables/pipes with no recipes set accept any items.

**Comment by SonOfTheStars** [comment]
Issue works as follows:
Provider pipe, set to "Leave 1 Per Type" provides Items from First Stack, jumps on to next stack and looses precision while doing that.
Resulting in Requested Amount-1 being Provided, Provider though marks job as complete

**Comment by davboecki** [comment]
Could also be caused by a broken lost item detection in addition to crafting modules and provider modules (pipes as well) not stoping sending items when all of their targets are full.

**Comment by SonOfTheStars** [comment]
Ove not recognised that as a poroblem by now, After 6 Hours of monitoring on the Server ive found that corner case there
Oversending is a problem too, but not when there is far less items requested into a LP-Crafter than it caN HOLD

**Comment by davboecki** [comment]
@Bitterholz https://github.com/RS485/LogisticsPipes/commit/57c5bdd3e31ee63dce83832df5635ae665ad7b05
Could you check if that changed anything.

**Comment by SonOfTheStars** [comment]
@davboecki All that stuff does, is completely disable LP´s ability to sink Items into my Chests now XD
all Modules that sink Items seem completely Broken!

**Comment by davboecki** [comment]
@Bitterholz Fixed that.

**Comment by SonOfTheStars** [comment]
@davboecki Now for the 0.9 Branch too pls :P Never going back to 0.8

**Comment by davboecki** [comment]
should be done. Updating that one takes a couple of minutes.

**Comment by davboecki** [comment]
@Bitterholz Any news on this?

**Comment by SonOfTheStars** [comment]
havent tested right now because there where some issues with the Testserver, though the Test shall start Today!

**Comment by SonOfTheStars** [comment]
I can confirm this is Fixed! Havent had an Locking Incident in 5 Days now.
