### ISSUE TITLE
Java crash when entering the world with b77

### ISSUE THREAD

**Issue by wormzjl** [RS485/LogisticsPipes#499]
Worked fine with b76
http://pastebin.com/nBH8uqv1

**Comment by AartBluestoke** [comment]
seems that the vm exceptioned during a GenCollectFull operation, started
while class loading was happening ...

would you mind updating your java version and test to see if that
continues; if there was an issue with our code, we wouldn't expect the VM
itself to error, only our code ... (also, i don't think anyone else has
reported this, so i'm not sure where else to start diagnosing this)

ps: (build 1.7.0_45) is from october last year, the latest version is
around ~build 72. 5 of the releases since then have been critical patch
releases, so i hope you're not browsing the web in a java capable browser
... This years Jan patch alone contained 4 critical issues (network
triggerable, no authentication needed, low complexity needed to trigger,
and resulting in complete access to all data on your computer) -
http://www.oracle.com/technetwork/topics/security/cpujan2014-1972949.html#AppendixJAVA

On Sat, Nov 8, 2014 at 9:30 PM, wormzjl notifications@github.com wrote:

> Worked fine with b76
> http://pastebin.com/nBH8uqv1
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RS485/LogisticsPipes/issues/499.

## 

“Getting information off the Internet is like taking a drink from a fire
hydrant.”
_– Mitchell Kapor_

**Comment by bziemons** [comment]
Also running a modded server with max ~1.7GB of ram might not be the best idea.
JVM crashes are not our fault in general.
