### ISSUE TITLE
[0.9] InjectItems now dupes Items!

### ISSUE THREAD

**Issue by SonOfTheStars** [RS485/LogisticsPipes#609]
The injectItems Method now fully Dupes Items that are Injected into the LP Network by any Machine with auto-eject.
Probably injectItems is returning the opposite of what it should, because the Original Items never get removed from the Output Slot of the Machine!
Confirmed with: 
- All Thermal Expansion Machines
- All EnderIO Machines
- All Buildcraft Machines

**Comment by davboecki** [comment]
Probably caused by me fixing a dupe bug for the TD interaction... :(

**Comment by SonOfTheStars** [comment]
I will intensivly monitor the parts you changed and hopefully get a quick solution.
I assume youre off to the same attempt.
So what was that dupe bug you tried to fix?

**Comment by davboecki** [comment]
This needs to be reverted: https://github.com/RS485/LogisticsPipes/commit/d112fa6fbb63615eaed2534fcfad4efbf36435c0#diff-805d19d56ed7ddc39e84e0291390ecc2L561
and this https://github.com/RS485/LogisticsPipes/commit/d112fa6fbb63615eaed2534fcfad4efbf36435c0#diff-e6242c7e7ae6672b21182d4668069b52R54 needs to be adapted.

**Comment by ArtForz** [comment]
The first part appears correct. Our transport.InjectItems returns the number of items rejected, tile.injectItem returns how many items were accepted - as BC tile.injectItem is supposed to.
Seems to me the problem is in https://github.com/RS485/LogisticsPipes/blob/mc17-0.9/common/logisticspipes/pipes/basic/LogisticsTileGenericPipe.java#L418
According to the TE API, insertItem is supposed to return the stack of _rejected_ items, while our injectItem returns the number of _accepted_ items. So we need to subtract the injectItem return value from the passed in stacksize in insertItem before the if blocks.

**Comment by SonOfTheStars** [comment]
Fixed!
https://github.com/RS485/LogisticsPipes/pull/613

**Comment by SonOfTheStars** [comment]
8ebce312269822a07eaf645646f5b85c9ec58130
