### ISSUE TITLE
Suggestion for improving beesinks

### ISSUE THREAD

**Issue by ab9rf** [RS485/LogisticsPipes#641]
It would be useful if beesinks could filter on the basis of the presence or absence of specific genes.

**Comment by ab9rf** [comment]
It would be useful if beesinks could filter on the basis of the presence or absence of specific genes.

**Comment by bziemons** [comment]
I am not into breeding bees anymore and I cannot really understand what you mean. Would you mind explaining a bit more around it? I am sure that some others might be thankful as well.

**Comment by SonOfTheStars** [comment]
what he mains is that he wants to have the Ability to route bees a certain direction if their Genetics match a certain Combination, e.g filterability on single/Multiple Genes like Flower Type or Production Speed

**Comment by hron84** [comment]
I think it would be hard to implement and hard to use too. What I really can imagine is a filtering based on a pre-selected single gene because it makes the GUI simple (e.g. you will not be restricted to only AND or OR conditions - if you place pipes right way you will get any type of filtering conditions). The important part is this gene filter should have a blacklist/whitelist switch.
