### ISSUE TITLE
"Import" button on applicable ItemSinks

### ISSUE THREAD

**Issue by Xuerian** [RS485/LogisticsPipes#650]
Seems like it would save a good bit of time in some common scenarios, were the button to read the current inventory and infer the settings from it.

Should apply to most ItemSink types, though that could be annoying to do. 

Yeah, a lot of suggestions. Setting up a system again.

**Comment by SonOfTheStars** [comment]
Polymorphic Sink allready and only does this. I almost only use Polymorphic

**Comment by Xuerian** [comment]
@Bitterholz They're similar, and could be used like that sometimes, but I'm only talking about initial configuration.

Polymorphic itemsinks are nice, but they're less useful when you want your storage to be resilient to emptying and are only storing one thing in a particular chassis. They're also more expensive, for obvious reasons.

This isn't a high priority suggestion, it's just usability. The kind of thing that wears you down more each time you set up a system that doesn't use AE as the backend.

**Comment by bziemons** [comment]
The thing I worry about is, that it would create an item sink module with a big number of sinking slots, because you can actually have as many different items in storage as the storage type gives you.

Also it gives the very easy one-click comfort button, which Logistics Pipes actually only has when you want to insert a recipe from NEI into your crafting table (now that would actually tedious to do manually). I myself build my storage without AE and I do not miss this feature.

**Comment by Xuerian** [comment]
I'm not suggesting any different _functionality_, merely reducing the number of clicks to set up exactly the same thing it does already.

My use case was ~50 barrels, which I already had stuff in. I have a terrible short term memory, so I was constantly going to the other side of the wall to figure out what I was working with in the 5-high stack.

With this button I could insert the sinks and "Import" the current contents - within the normal constraints of the ItemSink.

It really is just usability, but I guess I can understand if the amount of clicks to configure it is considered part of the balance, somehow..

**Comment by bziemons** [comment]
If you mean JABBA barrels: you can lock them to their content and then just use the polymorphic item sink, as that will work with JABBA barrels.

Also, I am not giving a final answer on this topic.. I am just describing my opinion. There should be comfort in Logistics Pipes of course. But advanced usage and possibilities always had a higher priority.

**Comment by Xuerian** [comment]
That's helpful to note (And explains what Bitterholz was talking about), thanks.

I still think this is a minor, valid usability improvement; though certainly not a required one.

**Comment by Silwing** [comment]
I think this would be a nice usability improvement too. And it should be pretty simple to have some fallback mechanic in case the inventory has more items than the item sink has slots. Either do nothing at all or simply choose the first encountered items. I personally think doing nothing would be appropriate since it is probably an error if you try to import and have too many items in the inventory already. But there might be a use case for selecting the first encountered items I'm just not seeing.

**Comment by bziemons** [comment]
Accepted in terms of an Import-button for only the item sink module (becase there are technical limitations with the basic pipe). That import button will take the first nine (or less) different items in the adjacent inventory to add them as sinks.

**Comment by hron84** [comment]
@theZorro266 btw, there is a bit problem about Polymorphic sink: even if you put them on barrels, you should configure Provider module to leave the last item in the barrrel or Polymorphic just forget what should it advertise regardless barrel is locked or not.

**Comment by Bitterholz** [comment]
Well configuring a Provider to "Leave 1 per Type" isnt that much of a Problem

It should keep you covered for both Chests and Barrels

**Comment by theZorro266** [comment]
@hron84 can you make a new issue suggesting to fix that behavior then? ;) It should be possible, as I suspect that JABBA would give us the right information.

**Comment by bziemons** [comment]
Removed the last three comments as they were off-topic and created #658 instead

**Comment by bziemons** [comment]
Implemented in e4cb0b0d50e80ff220773ace8b05f1a9ea706134 and therefor only in version 0.9.
