### ISSUE TITLE
Server Crash when Auto-crafting

### ISSUE THREAD

**Issue by keithmj89** [RS485/LogisticsPipes#652]
When I  submit for something to be crafted, it starts the process until it would pull an item out. At that point the server crashes, below is the most recent crash report.

http://paste.ee/p/7fIco

Thanks in advance for the help.=D

**Comment by bziemons** [comment]
You are probably using an old version of SuperMassiveTech, because as I can see at

https://github.com/tterrag1098/SuperMassiveTech/blob/master/src/main/java/tterrag/supermassivetech/common/handlers/AchievementHandler.java

tterrag1098 does have a check for that case (event.player instanceof EntityPlayerMP), so that error should not happen. @tterrag1098 may confirm this.

**Comment by bziemons** [comment]
Yup. I think this is already confirmed by tterrag1098/SuperMassiveTech/issues/13. That also loops back to #443.. what a mess.
