### ISSUE TITLE
Fix and enhance version tracker script

### ISSUE THREAD

**Issue by SonOfTheStars** [RS485/LogisticsPipes#657]
The Version Tracker of the 0.9 Branch still tracks the 0.8 Jenkins files, therefore allways claim being Outdated

**Comment by bziemons** [comment]
I would like to remove the version tracker entirely, as we have support for other version checking mechanisms.

**Comment by SonOfTheStars** [comment]
Lemme guess....Open Eye?

Jeah then just scrap that old version checker

**Comment by bziemons** [comment]
I was thinking about http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2091981-version-checker-auto-update-mods-and-clean
Because we have made an extra implementation for it here: #376 

The advantage is that we do not need a server-side script for that. That mod looks at Jenkins directly.

Other than that mod, there is also the NEM Version Checker that checks against the NotEnoughMods database.
Those are all newer implementation than our own check, so our own check was reasonable at the time @davboecki made it.

**Comment by SonOfTheStars** [comment]
I would prefer the Version checker Implementation we specificly made in https://github.com/RS485/LogisticsPipes/pull/376
that seems to me as the Best of all solutions.
And since you said it directly looks at the Jenkins, its the cleanest one too
And I love the auto update function of that Mod

**Comment by bziemons** [comment]
Well great, I was just reminded that we actually pass the information to that mod and it uses the very same script in the end. I thought it did magic.. :(

**Comment by SonOfTheStars** [comment]
Oh GG Zorro :D

**Comment by Casper-O** [comment]
Was going to complain about that 0.9 tells me there is a version 123 but seems like you guys are working on something new.. If you make some kind of auto-update, please let it be OFF by default

**Comment by hron84** [comment]
@Casper-O if it could be configurable via the new mod options GUI in-game, then I would like to see it ON by default. Just my $0.02.

**Comment by bziemons** [comment]
We now have a version notifier server that works with the newest versions. All the builds from the archive will get a notification about the newest stable build (on 0.9.2 right now).
