### ISSUE TITLE
BeeSink module can't identify bee/drone/princess for unanalyzed bees

### ISSUE THREAD

**Issue by swbrown** [RS485/LogisticsPipes#666]
The BeeSink does an isAnalysedBee() check in sinksItem() even if the filter result would not have required analysis (e.g. the alleles are left blank).  The drone terminus module is able to handle the equivalent 'is drone' check without analysis.

**Comment by swbrown** [comment]
Additionally, the beesink module should have an 'any analyzed bees' mode to allow for them to be on the same segment as an extractor/qsort and a bee analyzer module in extract mode without bounced bees from the analyzer getting misrouted (this still happens with qsort although that's a separate issue).

**Comment by davboecki** [comment]
It is intended that the sink module only works with analysed bees and the drone terminus also works with unanalysed once. Because you can do more with the sink module you need the bee to be analysed. This is to make it a little bit more challanging to use that module (you need the analyser). I don't see any reason to change that.
