### ISSUE TITLE
crash when rightclicking a facade

### ISSUE THREAD

**Issue by Turmfalke2** [RS485/LogisticsPipes#680]
hi,
I got this crash when shift right clicked a facade to remove it from a basic lp pipe.
http://pastebin.com/b4AywrnC

E: and I can reproduce it..

**Comment by SonOfTheStars** [comment]
Noticed this as well, but it only Sends me to the Main Menu. Its not a complete Crash for me. Just shutting down Internal Server(SSP) or Internal Server Error (SMP)

**Comment by Turmfalke2** [comment]
Oh sorry, yes that is what I meant. Crash as in crashs the server part. For some unkown reason it actually doesn't sends me to the main menu, but to the server selection screen, even thought it was a single player game.

**Comment by SonOfTheStars** [comment]
@Turmfalke2 thats because even though youre in SSp, your Client runs a Server behind. Thats why its "Shutting down Internal Server". Because there is the Sided Proxy thing in forge that allows to run Code only on either Server or Client. Like the Client does all the Heavy rendering and the Server does the Tile Entity Computations eg.
And because you TECHNICALLY have a Server Crash even in SSp, you get send to the Multiplayer server Selection Screen.

**Comment by bziemons** [comment]
Can you reproduce that with LP 0.9.1 and BC7 ?
