### ISSUE TITLE
Option to revert to old rendering

### ISSUE THREAD

**Issue by WolfieWaffle** [RS485/LogisticsPipes#713]
Personally I don't see the need for the new 3D models. They are more laggy, don't fit in with the buildcraft pipes, and sometimes glitch. I would like an option to use the standard textures that look the the BC pipes, maybe a config option.

I understand that you would probably need to restart minecraft to change the models setting and you would need two models for most pipes. But since you already have the textures for the old pipes, It would be very appreciated to allow using a simpler model. Mainly for lag reasons, but also for nostalgia/aesthetics.

Is this a possibility or would it be too much work?

**Comment by bziemons** [comment]
You can switch in the "Logistics Pipe Controller". Just right-click in the air, with the item in hand, and disable "Use New Renderer".

**Comment by WolfieWaffle** [comment]
Oh, cool I'll have to try that. Thanks :D

**Comment by WolfieWaffle** [comment]
One thing I WOULD like though is the ability to have it unchecked by default, rather than having to uncheck it in every new world. But I suppose that's being nitpicky, so It's fine :)

**Comment by hron84** [comment]
@theZorro266 it's a clientside stuff, or it works on SMP without any privilege?

**Comment by davboecki** [comment]
The information is stored on the server, but you don't need any permission to change the state. 
But the old textures will NOT become the default ones. Over time they may even be removed but that's not decided yet.

**Comment by WolfieWaffle** [comment]
So if one person changes it it changes for everyone? Would that mean that on a multiplayer server somebody could just switch it on and off over and over and annoy people?

I would like it to be a client-side config file option, or at least a client-side remote option, so that people could have their preference. Please don't remove the old textures, I like them. If you add a new pipe, I would try to create a new "old" texture for it, so you wouldn't have to work on maintaining two sets of textures.

Of course, you don't have to make a mod decision based off one person, I'm just giving my opinion.

**Comment by davboecki** [comment]
No the option is per player per server. So you can't annoy people.

It's not about the textures it is about the model. There is a new block type with a new model in works which can't be renderd with the old style.

**Comment by WolfieWaffle** [comment]
What? That first sentence was confusing. I'm assuming that means it's
player, which is good.

**Comment by hron84** [comment]
@davboecki I'm getting more and more confused about this too. We talking about a same block but different rendering, not? So, if I change the rendering mode it does not means I have to break-replace the block to get different model/rendering, right? 

Also, rendering and texturing sounds like as a clientside job. How it comes to the server? And why? Even if I am not completelly against to push some jobs to server side, classical mods are not push their rendering settings outside of the client, is there any way to keep it inside the fences?

**Comment by davboecki** [comment]
OK, to make it more clear:
The setting if you want to use the old rendering or the new one is saved inside your world. So that when you change the server you play on or the world you are playing in SSP you can have a different option for your render settings. [It's only the settings that are saved on the server]. There is no part of the rendering that is moved to the server. And no, you don't need to replace the block to get the new rendering. That's taken care of.

**Comment by hron84** [comment]
@davboecki "The setting if you want to use the old rendering or the new one is saved inside your world. "

To be more specific: in my playerdata, if I guess well. Well, this makes a clear situation then, even if I think there is more possibility to store these settings since - as I think - the render choice is a bit more client-specific than world-specific (I can imagine a person who uses same rendering settings on all of his worlds because the limited resources on one machine but an another rendering settings on a gaming-monster machine where other rendering looks more nice), but I do not know how you can change a config file setting in-game so it sounds as a good compromise for me.
