### ISSUE TITLE
Basic logistics pipe recipe

### ISSUE THREAD

**Issue by Patus** [RS485/LogisticsPipes#720]
Basic logistics pipe can craft from Unrouted transport pipe.

forge 10.13.4.1481
logisticspipes 0.9.1.15

**Comment by p-schneider** [comment]
The `Basic Logistics Pipe` can also be crafted from the `Logistics Request Table` - in that case it's the opposite of an exploit.

P.S.: Breaking the `Unrouted Transport Pipe` doesn't drop an item.

**Comment by p-schneider** [comment]
The original bug posted by @Patus has been fixed in [logisticspipes-0.9.1.142.jar (BC6.4)](http://minecraft.curseforge.com/mc-mods/232838-logistics-pipes/files/2247977) and [logisticspipes-0.9.2.18.jar (BC7)](http://minecraft.curseforge.com/mc-mods/232838-logistics-pipes/files/2248443), but the additional somewhat related issues in my comment above are still present.

related commit: aca20088a2dc4591b115e0c5a7cdba9b4c7accf9

**Comment by davboecki** [comment]
Unrouted Pipe drops are fixed.
I don't see why we should add more level of reset recipies for pipes. It would only add more recipes to the already really packed mc crafting system.

**Comment by Jean0** [comment]
Doesn't that mean you can now make basic logistics pipes without diamonds or gold?
