### ISSUE TITLE
BC Pipe speed

### ISSUE THREAD

**Issue by ghost** [RS485/LogisticsPipes#728]
Seems like speed is not improved from using gold BC pipes instead of Stone or Cobblestone pipes.  Actually it seems like its slower using the gold pipes.
BC 7.0.13
LP 9.1.15
Forge 1456

**Comment by bziemons** [comment]
Yeah.. I don't understand? Is this about Logistics Pipes?

**Comment by ghost** [comment]
Yes, this only happens when these BC pipes are used on LP network.  These BC pipes work as they're supposed to if they're just connected to BC extraction pipes.

**Comment by ghost** [comment]
Are the gold and stone BC pipes supposed to have same speed when used on LP network?  Is this the way it's designed?

**Comment by bziemons** [comment]
It might be the downside to having our item frames.. @davboecki knows more about this and can tell you, if it has to be this way.

**Comment by hron84** [comment]
I think no. Stone pipes - if you push an item to it on a BC way - are as slow as they are, but they do not slow down an item - it is exactly how they work in a pure BC system too. So, if you use a pure BC network, and you speed up your items with gold pipes, and transfer them with stone pipes, stone pipes will not slow them down drastically (actually, they do on a very-very long distance, but on short distances (20-40 block) it cannot be noticed). 

LP pipes pushes items at a bit higher speed than max speed of golden pipes, so if stone pipes slow down the item, it really hard to notice. 

It is based on my experience, but I welcome any fixes.

**Comment by ghost** [comment]
Stone pipes do slow down quite a bit in pure BC network.  Even on 10 block.  BC description is that Cobblestone is high drag which means it will slow them down.  Stone is medium drag and Quartz is low drag.  And you can clearly see the difference on BC network.  But on LP network, there is no difference.
I would have to think this is a bug or unimplemented feature because when connecting Thermal expansion itemducts to LP network, the ducts work at their designed speed.  Regular itemduct travels slow and impulse itemduct moves faster.

**Comment by hron84** [comment]
@taz1004 thanks for clarifying this, I am not very experienced in pure BC networks since I used them a very-very long time ago (around 1.5.2 or similar) maybe my knowledge is wrong.

However, ignoring BC drag effect is a tradition in LP-BC cooperation, at least it was the same situation in 1.6.4 so I am not sure it would be considered as a bug or as a feature. If LP introduces honoring BC pipe drag it would break systems that uses this... hmm... exploit.

**Comment by davboecki** [comment]
I suspect that with the speed we send our items trough BC pipes the gold pipes can't speed up the items anymore, they have a limit and by themselves they need a lot of pipes to reach that limit, but because we use LP power to speedup the items we go to max speed inside the LP pipe and for that reason reach the limit faster.
The box is just a rendering thing nothing inside the implementation really. And we give the item to the BC pipe and then the bc pipe is responsible for the transport. So we can't really change that behavior anyway.
As to the Thermal expansion speed. We don't tell them to move at a high speed and for that reason they behave normal.
I don't see a need to work on this in any way.

**Comment by hron84** [comment]
@davboecki I see. However, LP-sent items are not affected by BC drag speeds, do you think then it's a bug on BC side? Just to clarify things. If yes, I thinking to raise an issue for BC - just to let see what happens.

**Comment by ghost** [comment]
Since this, I've replaced all the BC pipes with basic logistics pipes and it's actually slower than cobblestone BC pipes?  Have you actually tested the transfer speed of all the pipes?  And in my personal opinion, the speed upgrade on the pipes seem a bit too expensive.

**Comment by hron84** [comment]
I dunno, but I'll check it.
