### ISSUE TITLE
TE Power Provider Exception

### ISSUE THREAD

**Issue by ishitatsuyuki** [RS485/LogisticsPipes#735]
A partial log for the error:
http://pastebin.com/zQWrCCG9
Then the item disappears from creative and NEI.
I don't think there is further log needed :)

**Comment by bziemons** [comment]
Versions of Forge, BC, LP and in this case your cofh mods, please.

**Comment by hron84** [comment]
@ishitatsuyuki also please describe what did you want to do when this exception happened.

Btw, if it is possible, we really appreciate if you use [Gists](https://gist.github.com) to upload logs since it's more readable and more reliable than Pastebin. Also you can upload even bigger logs to a gist.

**Comment by ishitatsuyuki** [comment]
OK, here you are:
CoFHCore-[1.7.10]3.0.3B2-294.jar
MineFactoryReloaded-[1.7.10]2.8.0-104.jar
ThermalDynamics-[1.7.10]1.1.0B2-149.jar
ThermalExpansion-[1.7.10]4.0.2B2-210.jar
ThermalFoundation-[1.7.10]1.2.0B1-95.jar
buildcraft-7.0.13.jar
buildcraft-compat-7.0.8.jar
logisticspipes-0.9.1.15.jar

Description of what i was doing:
Get the Machine from Creative Inventory and place it, then <bang>.
BTW, it doesn't disappear from survival inventory.
