### ISSUE TITLE
Local Game Crashes upon requesting a craftable item or its components. 

### ISSUE THREAD

**Issue by afloresescarcega** [RS485/LogisticsPipes#739]
log:
https://gist.github.com/hydrophilicsun/a30b109c8eb2d264d1f1

OpenEye's réponse (not that helpful in this case):
http://openeye.openmods.info/crashes/ce3f0550db4c7fdec3aef121c203fb64

I'm running LP pipes 0.9.1.15

I tried requesting auto crafting tables and this time it didn't work. It disconnected from the 'server'.
I logged back in and tried again. Same results. Restarted my client. Same results.

I also tried just requesting auto crafting tables components to manually craft them. Same results.

**Comment by hron84** [comment]
@hydrophilicsun could you test if you can craft autocrafting tables manually on a vanilla crafting table without involving LP?

**Comment by loordgek** [comment]
@hron84 plz read the log before posting

**Comment by afloresescarcega** [comment]
@hron84 Yes. I can manually craft them.

Something interesting to note:

line 13047

[10:30:50] [Server thread/ERROR] [FML]: PacketInboundHandler exception
java.lang.IllegalArgumentException: zero count needed, promises not needed.

and on line 13091:

[10:30:50] [Server thread/ERROR] [FML]: There was a critical exception handling a packet on channel LogisticsPipes
java.lang.IllegalArgumentException: zero count needed, promises not needed.

I'm a strong believer in the end user meeting the developer/s half way for a fix.  Please don't hesitate to ask for more info.

Also, if an active supplier fulfills the request, the game fatally crashes.

**Comment by hron84** [comment]
@loordgek I read the log, but I wasn't sure it's when the autocrafting table was requsted or when he tried to craft it in a Request Table. That's why I asked him to try to craft it manually because I guessed the error is somehow happens when the game tries to render the autocrafting table as an item in the result slot. Since I amn't a developer I can work with just guessing.

**Comment by hron84** [comment]
@hydrophilicsun Since you mentioned you already have an autocrafting system (because you said you tried to request an autocrafting table and its parts from the LP network) I just want to ask only one more thing: what did you change in mods since you made your autocrafting system? Maybe one or two mod got an update or similar?

**Comment by afloresescarcega** [comment]
Changes have been made probably a few days prior to this error. Autocrafting was all and well and then this happened. 

I will suggest a mod: Sim-u-kraft Reloaded. This mod's removal was the only change to my mudpack in weeks. It doesn't interact with any mod but with itself.

**Comment by afloresescarcega** [comment]
@theZorro266  @hron84 Found the cause!

Cause: http://imgur.com/PaZzo41

Wooden planks were requested through my system. I had wood blocks. I taught myself in a FUZZY auto crafter that any OreDict wood would produce oak planks.

Recipes in my system that needed planks had a fuzzy OreDict wooden planks, meaning it could accept any type of wooden plank.

So what does this all mean? My game crashes when it requests OAK wooden planks by using spruce wood. 

Close this issue if you want. This might be another issue entirely with Fuzzy Crafting exception handling.

**Comment by bziemons** [comment]
Thanks for finding that! The issue is fine as it is.

**Comment by davboecki** [comment]
@hydrophilicsun Could you also make a screenshot of the connected crafting pipe ?

**Comment by Sakata-MC** [comment]
Hey guys, ltns.
Here is an error log that I got, similar crash but different reason from what i gather.
Don't have any oredict stuff... so this one is new for me.
**_Does not give any error on client side**_
http://pastebin.com/f1YS0QhG

**Comment by Sakata-MC** [comment]
This time it actually crashed the server.
http://pastebin.com/wDxrKDhX

**Comment by HadesDurin** [comment]
update to latest version and try again
see if it still crashes

**Comment by Sakata-MC** [comment]
@HadesDurin FYI, I'd already checked on that but since it's not in change-logs, and this issue is still open, I'd already reasoned that to be irrelevant, which it is.

Getting the error for each version after the current included one in FtB:I, which is what the server is using. I can easily update this but unfortunately doing so makes no difference so is not worth the effort of changing everything around to manually update quite yet.

I'm not quite sure as I'm still testing things out but I believe this to be an issue with either the ability to choose the output for a recipe, or the crafting module (one step is furnace recipes, which use a chest/redstone furnace with a chassis+modules and a satellite pipe [I have noticed crafting module doesn't seem to retain in the GUI the satellite pipe used, but seems as if in memory it is correct]).

Thus-far I have determined it to have something to do with complicated recipes, but can't put my finger on the exact cause.  In one instance of testing, I'd crafted a Redstone Solar panel from Solar Expansion, with no issues, but then later when requesting the same thing again, it would crash with the above error.

It almost seems as if something is happening with the table, or perhaps some memory issue.  I find it very odd that there is the error in the server error log, but the client only gets a network exception and is kicked from game with no indication as to why in the client logs.

Possibly related:
#736

**Comment by davboecki** [comment]
@Sakata-MC Your issue has nothing to do with this one. You have a simple class case exception. Please open a new isse for that.

**Comment by Sakata-MC** [comment]
Really?  Cool. The symptom is the same though so figured it was similar, and these two lines are also in the server errors:
https://gist.github.com/Sakata-MC/7e2336263d7676be439a#file-crashola

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/ce7e4d7e0a03e03f9a527371f70d2d55764df339
