### ISSUE TITLE
weird crafting behaviour

### ISSUE THREAD

**Issue by Nex4rius** [RS485/LogisticsPipes#769]
https://www.youtube.com/watch?v=cIDmU4FW-rc&feature=youtu.be

logisticspipes-0.9.2.19
gregtech_1.7.10-5.08.25
NotEnoughItems-1.7.10-1.0.5.111-universal

**Comment by theZorro266** [comment]
Can you reproduce that with the standard non-fuzzy crafting table?

**Comment by bziemons** [comment]
NEI does not provide the NBT data which is needed for the recipe. This is the mod's fault, but not ours.

**Comment by DarknessShadow** [comment]
"mod's fault" NEI or gregtech where should T report it?

**Comment by bziemons** [comment]
Just because you have the right to open issues on GitHub does not mean you should do that on every related mod I just mentioned in my previous comment.
We use what NEI provides, what other mods provide to NEI. It's a chain, and not we nor NEI can change something about that. There always was a similar problem with IC2 batteries.

**Comment by Nex4rius** [comment]
> Just because you have the right to open issues on GitHub does not mean you should do that on every related mod I just mentioned in my previous comment.

But you said you cannot fix it. Does that mean I can now forget about it and you report it to the other mods?

> We use what NEI provides, what other mods provide to NEI. It's a chain, and not we nor NEI can change something about that. There always was a similar problem with IC2 batteries.

Did I find an unfixable bug?

**Comment by bdew** [comment]
From a cursory look it seems that the issue is that some items in GT get an NBT tag when crafted while the recipe does not includes said tag.

In most crafting systems NBT tags are ignored in recipes (e.g.  ShapedRecipes.checkMatch in vanilla, OreDictionary.itemMatches in forge, etc.) - does LP really need to check it?

**Comment by Nex4rius** [comment]
We already have the option to Ignore NBT in the Input of recipes why not also add that option for the output? (and for request tables)
