### ISSUE TITLE
Crash on world load from corrupt player config [LogisticsPipes{0.9.1.16}]

### ISSUE THREAD

**Issue by Mr-Turing** [RS485/LogisticsPipes#770]
Hi, been seeing a whole bunch of crashes such as this: https://gist.github.com/theZorro266/af4c97b00b4f148cb114

Check around link 750.
Has been reported from users that haven't even touched LP yet.

Deleting the logistics pipes folder on the save seems to allow the save to be loaded again.
Is this a known issue? Any more info I can provide?

**Comment by bziemons** [comment]
I have cut the logfile to the relevant part. Next time please use https://gist.github.com as that paste website you used does cut off line numbers and is incredibly slow for me.

Now to the actual exception: I have not seen that yet, and it seems to be caused by file corruption of one of our player configuration files (in this case the one in `<world>/logisticspipes/names/<player-id>.info`). We use the Minecraft class CompressedStreamTools to read and write those data files. It might be that something else interrupted the saving of the specified file and it was therefor corrupted, but that seems to be the only possibility how and why this could have happened.

That does not seem like a bug to me. Deleting the file should solve the issue, as you described. And I cannot imagine that this happens often. If it does happen more often, I would need a log that shows how it fails writing that file and not reading it.
