### ISSUE TITLE
Logistics Pipes not respecting Storage Drawers settings.

### ISSUE THREAD

**Issue by CXWRTH** [RS485/LogisticsPipes#808]
Some issues I have noticed. Not sure the exact reason:
- Logistics pipes will not respect full state. Continues to stuff pipe, dump items on ground.
- Logistics pipes will not respect void upgrade. Treats storage as full (dumps items on ground) even if storage drawer has void upgrade and should be voiding excess.
- Logistics pipes will not respect lock status. Logistics pipes will force items into "empty" drawers even if drawers are locked.

FTB Infinity: MC 1.7.10
Logi Pipes 0.9.2.29
Storage Drawers: 1.5.12

**Comment by hron84** [comment]
Could you check the latest LP version too?

**Comment by CXWRTH** [comment]
Just tested with 0.9.2.46 from http://ci.thezorro266.com/job/LogisticsPipes-0.9-mc17-bc7/

Same issue.

http://i.imgur.com/wNrNGdi.png

**Comment by hron84** [comment]
@Spasticon thanks for the test. Weird issue anyway.

**Comment by 1n5aN1aC** [comment]
I have tested this on:
LP 0.9.2.46
Storage Drawers: 1.5.12

I do not have the issue with LP continuing to try and stuff items into a drawer controller that has no space for that item.   This interaction works perfectly for me, both with oredict sinks, and regular itemsinks.

I DO have the void upgrade issue.  LP will consider the drawer network full, and send items elsewhere (fulling up my general storage area) when the drawer controller should accept the items. (and then delete them)

I do not have the issue with logistics pipes overwriting a locked (but empty)  drawer with that the pipe inserts into it.  NOTE:  I have not tested this directly, only via drawer controllers.  
HOWEVER, a polymorphic itemsink will not work with empty but locked storage drawers.  This would be a very nice compatibility update, but I can definitely understand why it works that way in the absence of specific interaction code.

**Comment by leglerm** [comment]
Getting some interaction issues also.

LP: 0.9.2.46
Drawer: 1.6.1

Using a Basic Logistic Pipe at a Drawer with Void Upgrade. Items get send to it but the void upgrade gets ignored so items will be routed back into the system (using a terminus at void chest for the moment). 

Don't have Jabba installed but maybe someone could test it out there.

**Comment by 1n5aN1aC** [comment]
These issues have all been fixed or implemented:

`Logistics pipes will not respect void upgrade. Treats storage as full (dumps items on ground) even if storage drawer has void upgrade and should be voiding excess.`
Fixed in https://github.com/RS485/LogisticsPipes/pull/833

`Logistics pipes will not respect lock status. Logistics pipes will force items into "empty" drawers even if drawers are locked.`
This was fixed in StorageDrawers:  https://github.com/jaquadro/StorageDrawers/issues/163

`A polymorphic itemsink will not work with empty but locked storage drawers.`
This was implemented in https://github.com/RS485/LogisticsPipes/pull/839

`Logistics pipes will not respect full state. Continues to stuff pipe, dump items on ground.`
This one I have not been able to confirm at all, no matter how hard I try, except in conjunction other issues, so I'm relatively sure this one has been fixed.  I just haven't ever been able to reliably produce it before, so I can't be 100% sure.
