### ISSUE TITLE
[Request] Make placement rules for power transportation upgrades follow the same logic as basic pipes

### ISSUE THREAD

**Issue by HCSarise** [RS485/LogisticsPipes#822]
What is the reasoning behind needing a power transportation upgrade at every turn in your pipe system rather than every junction? It results in me needing to be super careful about lining up pipe systems exactly and perfectly unless I want to waste a bunch of extra resources and also needing to place otherwise pointless basic logistics pipes so that the upgrade can be applied. Seems like it would make more sense to me to need a transportation upgrade at every junction, just the same as you need a basic logistics pipes at every junction.

**Comment by SonOfTheStars** [comment]
Did you ever see lasers go arround corners by themselfs? No?
Question answered :P

**Comment by davboecki** [comment]
This was more a question about some sort of balance. So this was a design choice we made and I think we will stick to it.

**Comment by hron84** [comment]
@HCSarise it is needed because I think it brings the system close to reality. If you think in a mirror-system, the (laser) light can go only on straight line and usually does not turn unless it faces with a solid object or liquid. If you want the laser to turn, you have to have a mirror at the edge to enforce the turn. That's why you need this upgrade at every turn, basically you install a mirror onto your pipe to make the laser turn - otherwise it would just go out on the side of the (glass) pipe to nowhere, wasting your power :-)

**Comment by HCSarise** [comment]
Fair enough, just curious. Thanks guys :)
