### ISSUE TITLE
Smeltry Interface Pipe (Alloy Crafting Pipe)

### ISSUE THREAD

**Issue by mikeloeven** [RS485/LogisticsPipes#844]
So an issue I came across was the fact that the Tinkers Smeltry has a rather major issue when dealing with fluid systems which breaks the fluid request pipe. When I posted on the TK Git they essentially said works as intended / Wont Fix so i was hoping that logistics pipes could add support for smeltry automation by adding a new pipe for handling alloy crafting as well as overriding the fluid extraction methods at the provider pipe level.

Any way i would like to see a Liquid Crafting Pipe that can support liquid crafting requests and automatically pump variable amounts of molten metals into the smelty and extract the resulting alloy. Additionally due to more fluid crafting across all mods fluid pipes should be able to support multiple fluids and default destinations as well as having the fluid request pipe override the extraction methods in the smelty drain/controller to allow it to bypass the smelter limitation of only extracting the bottom metal/alloy

**Comment by loordgek** [comment]
is this wat you want? https://github.com/RS485/LogisticsPipes/issues/635

**Comment by mikeloeven** [comment]
Not exactly its more about the ability to override the smeltry's default fluid handling as well as the ability to handle multiple fluid types on a single pipe

**Comment by loordgek** [comment]
wat is the problem w/ smeltry's fluid handling? 
can you post the link to your TK issue

**Comment by mikeloeven** [comment]
This is actually the lesser of the issues but its still something i am hoping the fluid provider can bypass with some tweaking

https://github.com/SlimeKnights/TinkersConstruct/issues/1785#issuecomment-150841958

the main issue though is that we should be able to set a smeltry as a default fluid destination since it can hold decent ammounts of multiple fluids and could serve as a temporary storage space and prevent the fluid system from clogging when processing large amounts of ore also a pipe that allows you to craft alloys directly by requesting the resulting fluid without needing 10's of pipes

**Comment by hron84** [comment]
@mikeloeven Did you take a look for Tinkers Steelworks' Deep Tank? If I know right, it can store multiple fluids too w/o alloying option. Also, ExtraCells are always an option to store multiple fluids in few blocks.

My personal opinion is not overriding Tinkers Smeltery mechanics because it can break the mod and/or its balance. Also, I do not think LP should be this obtrusive. "Integration" is never meant to modify existing basic mechanics. Alloying is the nature how smelteries work, and this should be never changed. With smart filtering your target can be achieved by current stuffs too (just do not use the dumb default routing, but instead filter all alloyable metals to different smelteries/tanks, and make one more smeltery for the remaining.

**Comment by bookerthegeek** [comment]
If I'm reading everything correctly, he wants the ability to be able to override the requirement for the extracted fluid to be on the bottom of the smeltery. So for example if you have both gold and iron in a smeltery you could use LP to pull either of them out without going into the smeltery and moving the requested fluid to the bottom.

As it stands now iirc the LP system can only see the bottom flyid, and also can only extract the bottom fluid since it is the only one it can see.

Workaround would be to use the smeltery as intended as a pulverizer/furnace and not as a tank. Use tanks. Or set up a smeltery for each fluid your looking to store.

**Comment by bookerthegeek** [comment]
As for creating alloys in a pipe, that would be overriding TK  functionality, most likely not going to happen.

**Comment by hron84** [comment]
@bookerthegeek now I see. However, I still think we should not modify any behavior of the smeltery since it is simply not how it is intended to work. If we really want to modify a functionality, do it with Tinker's Steelworks Deep Tank since _this_ stuff is intended for store multiple fluids in a multiblock. If we do that we can be pretty sure we do not break any more difficult game mechanic like alloying or smelting mobs. 

But, this is just my honest personal opinion. Ignore me.

**Comment by bookerthegeek** [comment]
Oh no, I personally  think this idea is horrible. As do the TC devs. The OP basically wants to have the TC mod work in a way against the ideas of the mod devs because he finds it difficult to automate. After being told no by the tinker construct devs he came here hoping to get the LP devs to do it anyways. 

/Rant

**Comment by mikeloeven** [comment]
I dont see the issue i am looking for something annoying to be more eaisly automated if the TK devs dont implement it i see no reason why another mod cannot provide the needed functionality. After all the issue with the smelt only outputting the bottom liquid may be intended but it breaks the intended function of fluid providers

**Comment by loordgek** [comment]
i agree w/ @hron84 do not mess w/ other mods

**Comment by loordgek** [comment]
you can automate it but dont use it as a multi tank

**Comment by bookerthegeek** [comment]
It does not break the intended behavior of the fluid provider. The fluid provider will provide fluids that are PROVIDED by the said tank. (Yes, the smeltery is a tank). The tank in this case is only providing the fluid on the bottom. This is the intended mechanic of both mods. 

If anything, LP could modify the provider pipe to only show the bottom fluid and not every fluid in the tank. This is probably not really a bug, just an enhancement. 

And the needed functionality you are looking for goes directly against the ideas of the other mod. Your asking LP to basically tell the TC guys that they don't care about your ideas on how the mod should work, and we're going to override you.most likely not going to happen.

If it really bugs you, make a mod that adds a multi fluid tank that you can access any fluid stored on demand remotely. Or just store the mutant fluid in buckets in your storage system and craft with those.

**Comment by bziemons** [comment]
I agree with @bonii-xx over at https://github.com/SlimeKnights/TinkersConstruct/issues/1785
Because this is automatable in other ways (the smeltery should not be used as a big tank for automation), I do not see a need for this.
Also I agree that we should not touch other mods, if not necessary. The list of integrations is long and incompatibilities happen especially in these cases, where the API is not enough.

Also, I agree with @bookerthegeek

> If anything, LP could modify the provider pipe to only show the bottom fluid and not every fluid in the tank. This is probably not really a bug, just an enhancement.
