### ISSUE TITLE
Eliminate BC dependency?

### ISSUE THREAD

**Issue by NightOps007** [RS485/LogisticsPipes#875]
I don't know how heavily LP is dependent on BC api, but would it be possible to make LP independent while still keeping the compatibility with BC pipes? I just thought I would put the idea out there since I've heard that the conversion to MC v1.8.8 will require most mods to undergo a major overhaul.

**Comment by SonOfTheStars** [comment]
Its allready there!
Well at least recipe and Transport Wise...You can use Unrouted Transport Pipes instead of your Standard BC pipes. You can (in the config) enable the BC-Independant recipes. BC still needs to be Installed and I fear before LP Gets independant of BC we should rather make Logistics Pipes 2 without BC completely and more structured.

**Comment by bziemons** [comment]
This was discussed a few times and does not make sense right now. Many parts of LP are already independent of BC.
