### ISSUE TITLE
Storage Drawers - Not all items can be requested

### ISSUE THREAD

**Issue by nrzimmer** [RS485/LogisticsPipes#880]
I have a single storage drawer controller and i have a problem with some items.
They just doesn't show on the logistics request table (and any other request method).

The images above show 2 examples of the bug.

I'm using the FTB Infinity Evolved modpack (Version 2.2.2)
Logistics Pipes 0.9.3 (BC7) Build 70
Storage Drawers 1.7.2

Cant' find Tin
![1](https://cloud.githubusercontent.com/assets/3421735/11982585/bd92d286-a993-11e5-885c-1a53274cef9e.png)
![2](https://cloud.githubusercontent.com/assets/3421735/11982564/8d8a0e24-a993-11e5-8ca3-da5ae5002ada.png)

Can't find Refined Iron
![3](https://cloud.githubusercontent.com/assets/3421735/11982565/8d8e68fc-a993-11e5-8dec-5fc96747fff2.png)
![4](https://cloud.githubusercontent.com/assets/3421735/11982566/8d949e7a-a993-11e5-9c23-1da3839434ef.png)

**Comment by hron84** [comment]
What if you move them closer to the controller? Keep in your mind, controller's range is limited to somewhat 15 blocks or so, so even if you have a consistent line/wall of drawers, it can be possible to controller is not able to find specific items. And since most ppl hooks LP system to the controller (and I guess you too), LP can only see what controller can see in this case. So double check your exact setup, count drawers carefully, and check if controller can take these items from your inventory if you right-click few times on the controller.

**Comment by nrzimmer** [comment]
They are in range, if i right click the items are stored. Actually, the Refined Iron Drawer was one column and 3 rows away from the controller.

I found out that removing the pipe, or the controller and replacing them make it work.
But this isn't the expected behavior.

Another strange thing is that the logistics (sometimes) remove the items from the drawers but they doesn't refresh, leaving a false storage amount.

**Comment by bziemons** [comment]
Re-implemented in https://github.com/RS485/LogisticsPipes/commit/fc0bb26d82c9872343634499429f86a04a83dd15

Hopefully fixed all problems mentioned here
