### ISSUE TITLE
Tesseract vs chassis with QuickSort bug

### ISSUE THREAD

**Issue by alexanium-dev** [RS485/LogisticsPipes#886]
FTB Infinity Evolved 2.2.2 (LogisticsPipes 0.9.3.70).

If tesseract directly attached to chassis mk4 with QuickSort module, tesseract won't accept sended by QuickSort items (provider module works fine). If I add basic logistics pipe between tesseract and chasis - QuickSort can normally send items.

**Comment by Timeslice42** [comment]
Wouldn't having the quicksort module directly attached to the tesseract cause it to attempt to sort the contents of the tesseract? (Which is of course not possible.) I don't remember if the quicksort module is directional, but look on the chassis pipe for an orange pip. Use a wrench on the side of the pipe that the inventory is attached to so that the orange pip is only on that side.

**Comment by bziemons** [comment]
This issue does not make sense to me. A chassis pipe needs to be attached to an inventory by definition. The tesseract clearly is not an inventory and to function as a teleport point in a logistics system, it needs to have only one basic logistics pipe attached.
I am closing this. If you still think there is an issue with the behavior, please open a new issue.

**Comment by hron84** [comment]
@theZorro266 a simple question around this: tesserracts can act as a valid stuff for Logistics Inventory Connector?

**Comment by bziemons** [comment]
@hron84 No, I don't think it works that way. You just connect a basic pipe to each of the two connected tesseracts and you would have the same effect as with the inventory connector and e.g. an ender chest.
The Logistics Inventory Connector is only meant for inventories. It might work with the tesseracts as well, but then it would act as a basic logistics pipe. It would not even need the connection cards in that case.

**Comment by hron84** [comment]
Cool, thanks for letting it know.
