### ISSUE TITLE
Is Logistics Pipes Dead?

### ISSUE THREAD

**Issue by SonOfTheStars** [RS485/LogisticsPipes#903]
Just a quick sanity check:
@davboecki @theZorro266 you guys still alive?

If not, LP needs to be passed on!

**Comment by SonOfTheStars** [comment]
OK the Jenkins vanished...this aint lookin good!

**Comment by bziemons** [comment]
The server hoster thought it was a good idea to restart the server yesterday. Jenkins was not in autostart. So much for that.

**Comment by hron84** [comment]
I hope this project is still alive :smile:

**Comment by loordgek** [comment]
@Bitterholz can you not help ?

**Comment by SonOfTheStars** [comment]
Well so @theZorro266 how much are you and @davboecki still working on the project...its been quite quiet the past weeks...PR's stall arround n shit...
Do you guys have no time anymore or whats Cookin?

**Comment by Ioandar** [comment]
Just wanted to express a big **thank you** to all who worked on LP. 

It has always been one of my favourite mods (i am now on 1.8.9). Seeing Items zipping all around my base is something so awesome cool and I really really miss LP. I wish LP will at least continue on 1.7.10 because I know many people who are (like me) totally thankfull for this great work of yours!

**Comment by ghost** [comment]
1. LP is under a rather permissive license. No permission or "passing on" needs to take place. The only condition is that modified copies make their source code public and use the same license.
2. 2 weeks is not enough time to declare a project dead. We have had mod authors reappear years after last contact. davboecki and theZorro266 are likely busy with real life.

**Comment by hron84** [comment]
I'm pretty sure they want to work on LP, as there's so much upcoming coolness and the mod itself is also very popular that usually inspires all authors to work toward on the project. Also, I'm sure if the LP will die anytime, one of the mod authors will announce it publicly.

**Comment by SonOfTheStars** [comment]
Me and some friends of mine, all quite the Fan of LP, have actually made plans for a Spiritual Successor of LP for 1.8...
I presented the ideas to a Few ppl familliar with LP and they liked them. im not quite ready to deliver a design Document because i need to get more indepht with MC 1.8 Modding first.

To tell you guys how far we got: Defenition and rules have been made, alot of improvements on Rendering and Server perf are planned, full modularisation and alot of indepht Features.

Also got a Basic modell Goin, take a look:
![center-textured](https://cloud.githubusercontent.com/assets/3910862/13035997/12e39db4-d35c-11e5-9878-ba52a68af1c4.png)
![base-modell](https://cloud.githubusercontent.com/assets/3910862/13035998/17707b72-d35c-11e5-8371-b8aeb0cb3f09.png)

Getting this Goin in 1.8 is kinda hard tho so dont expect this to be arround anytime soon

**Comment by loordgek** [comment]
@asiekierka can you help @Bitterholz w/ the rendering

**Comment by SonOfTheStars** [comment]
i dont even think the modell can be loaded due to the Triagonal faces on the Sides of the Center

**Comment by asiekierka** [comment]
Use .obj... Look for the rendering primer.

**Comment by SonOfTheStars** [comment]
Rendering Primer?
Allready use OBJ but im getting MultiModel "modID:Model_Name".obj is empty (no base model or parts were provided/resolved)(Happened after I textured the Core Part and the addition of a Second Material to make the Glass transparent)
Before the texturing, it did load the model, but showed an empty 1x1 Block BB, Now its a full block of Missing Texture

...Does it HAVE to be devided into groups?

Maybe I should let some more experienced in Blender take a look at it...

**Comment by bziemons** [comment]
Maybe you should move that discussion in a forum or an issue of your own repository? 
Just a thought, because that seems quite off topic for this LP. I do encourage moving on, but I agree with @hron84 and @DZCreeper: I would still love going on with LP and LP is open source under a permissive license. Such a project is unlikely to be "dead".
Also: if anyone jumps in and does good work on the mod, I am happy to update the Mc forum thread and provide our Jenkins as build service.
Because of that, I would like to close this issue.

@davboecki is on the same page, as he would like to work on the mod as well, but can't due to work and studying.
