### ISSUE TITLE
Logistics Pipes crash with Thermal Dynamic 1.2.0B1-167

### ISSUE THREAD

**Issue by Drethic** [RS485/LogisticsPipes#910]
I just updated to the latest version of Thermal Dynamics (1.2.0B1-167) and I'm getting this error:
http://pastebin.com/YQYr6iSN

**Comment by SonOfTheStars** [comment]
Seems like we need to update the Thermal Dynamics Access Transformer once the new Version gets an OFFICIAL release. Aplha versions are /UNSUPPORTED/!
Thanks for reporting!

**Comment by bziemons** [comment]
@davboecki shouldn't just the proxy be disabled?

**Comment by davboecki** [comment]
There ASM involved so: no it's not just disabling the proxy.
We need to check what method changed and then see if it still works like intended and add the method hash to the allowed hashes.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/ca7c551f9c13d2287dca8e67902d06fe7655e91b

**Comment by Manuepolis23** [comment]
still not working

**Comment by davboecki** [comment]
If it's still not working could you post a new crash report please.

**Comment by Manuepolis23** [comment]
it is the same I think
http://paste.ee/p/OiqqR

**Comment by davboecki** [comment]
Because our Proxys are embedded deep inside LP. So handling that with mixins and even only the part about a reperate repo would increase the workload drasticly if you want to fix something with out mod integration.
And for the time beeing if there is a mod that's not updated and we don't want to shoot into the dark with the compatibility we can simply disable the compatibility and just fall back onto the dummy proxy untill that mod updates.

**Comment by davboecki** [comment]
It's not the same. But https://github.com/RS485/LogisticsPipes/commit/3ac5287d24fc5812d659eeb34827e1d77e490802 fixes that.

**Comment by Manuepolis23** [comment]
Now it is ok.Thanks.
