### ISSUE TITLE
Voided storage drawers bug

### ISSUE THREAD

**Issue by zogarr** [RS485/LogisticsPipes#936]
#808 seems to be broken again in the latest Infinity.  Instead of going to my polymorphic itemsink to a voided drawer it considers the drawer full and instead is sending the item to the default route.

Playing FTB Infinity 2.4.1 Expert Mode with Logistics Pipes 0.9.3 Build 87 and Storage Drawers 1.9.2.

**Comment by davboecki** [comment]
This is a Storage Drawers problem not realy an LP one. I added a workaround for now, but please report this to them as well.
https://github.com/RS485/LogisticsPipes/commit/f098b67f4e86c96a827da37d8626470c530e9603

**Comment by zogarr** [comment]
OK - I will report it there.  It is possible it is fixed as there has been updates since 1.9.2.  I will try with the 2.4.2 infinity which just came out - and it has storage drawer updates.

**Comment by davboecki** [comment]
Make sure to test with an LP version below 0.9.3 Build 97. Otherwise the implemented workaround will hide the issue.

**Comment by jaquadro** [comment]
I don't think this ever got reported to SD, but mentioned in https://github.com/jaquadro/StorageDrawers/issues/113#issuecomment-217766377 the workaround has caused other routing regressions.

**Comment by jaquadro** [comment]
I did some testing with Build 95, which should be just before patch.  Basic setup is drawers on a controller, pipe with a polymorphic item sink, pipe with extractor mk3 attached to a chest.

Void upgrade seems to work fine, as it would continue to pull items from the chest and void them even if the void inventory was at capacity.  Maybe necessary LP infrastructure needed to produce the issue is more complex, but that's the extent of what I can test.

Other than breaking precedence as mentioned in the above linked comment, I'm nervous about anything that calls both enumerateForInsertion and enumerateForExtraction.  Using the wrong one is probably a recipe for an exploit.
