### ISSUE TITLE
Automatic Arcane Workbench

### ISSUE THREAD

**Issue by Maggi123** [RS485/LogisticsPipes#958]
It would be cool to have an automatic arcane workbench so you can automate it. Don't know if it is possible tho.

**Comment by AEnterprise** [comment]
i thought there was an addon for that already

**Comment by loordgek** [comment]
for ae2 yes cant find one for lp

**Comment by loordgek** [comment]
@davboecki or @theZorro266 can you look at this ASAP i need it now

**Comment by hron84** [comment]
It needs a lot of connection with thaumcraft, I bet it will be a big feature.

**Comment by bziemons** [comment]
@loordgek that is some egoistic attitude there. You better try to do it yourself then.

**Comment by Maggi123** [comment]
Just another idea: Arcane Logistics Request table. You can do arcane crafting with stuff in your LP-network.

**Comment by hron84** [comment]
Guys, a whole separated mod bornt for Applied Energistics, why we want to include it in LP anyway? This is not a "support Thaumcraft aspects" feature, it needs a whole integration with TC, including new researches, messing with TC mechanics. I'd really love if a mod like this would be a thing, but... I'm definitely not think it should be made inside LP.

The better question is LP has all the API that let anyone to make a plugin for it that digs into the deeps of LP? Because in LP side, as far as I know we need a support for a custom logistics crafting table, adding a support for Vis relays for the new crafting table, transporting essentia for Crucible-based recipes inside LP network based on crafting requests, and so on. So, what could be possible with the current API?

**Comment by bookerthegeek** [comment]
@hron84 That is a good question.
