### ISSUE TITLE
Jenkins Mislink

### ISSUE THREAD

**Issue by lewisakura** [RS485/LogisticsPipes#960]
Attempting to go to Jenkins, it refuses the connection. I also tried just going to `thezorro266.com` with no luck.

**Comment by bziemons** [comment]
The address is http://ci.rs485.network
Is the old address linked somewhere?

**Comment by Landrash** [comment]
@theZorro266 In the README.md the old adress is listed. You got a pull request to fix it  =)

**Comment by bziemons** [comment]
@Landrash merged. :+1:

**Comment by Landrash** [comment]
Missed one in the code. Unlikely anyone will se it but updated it also.

**Comment by lewisakura** [comment]
Also, was seen on the main post for Logistics Pipes.

**Comment by Landrash** [comment]
@LewisTehMinerz  Main post as in where?

**Comment by lewisakura** [comment]
@Landrash Minecraft Forums, the download links all link to that website. {e.g. Current Versions links to `http://ci.thezorro266.com/view/Logistics%20Pipes/`}

EDIT: Technically, Jenkins is not down, but rather a mislink.

**Comment by hron84** [comment]
@theZorro266 bringing down the ci.thezorro266.com address is intentional btw? Is there any way to put it back? Just curiosity.

**Comment by bziemons** [comment]
@hron84 the plan is to fade that address being related to Logistics Pipes actually. So instead of thezorro266.com, I want to use rs485.network. In the past few weeks we migrated to another server (and a completely different structure on that server) and because of the lack of time, I didn't check every address. That's why there was a problem. I fixed this one yesterday though.
