### ISSUE TITLE
Could not auto craft using buildcraft gates as ingredient.

### ISSUE THREAD

**Issue by ZZaphodd** [RS485/LogisticsPipes#968]
![image](https://cloud.githubusercontent.com/assets/8099421/14559493/230aa88c-0344-11e6-9890-a991092d4e45.png)

I try to autocraft some item using buildcraft gate as ingredient like above but it does not work.
I placed fuzzy logistics autocraft table, connect to network using craft logistics pipe and try serveral flags (damaged, use NBT,) on the "Basic gate" slots,
But request pipe still says "need 2 Basic gate".

I have a few stack of "Basic gate" and I can see them same request pipe try to auto craft.

modpack : ftb infinity skyblock 1.04

**Comment by SonOfTheStars** [comment]
Did you shift-click the Recipe in via NEI?
Because that often causes the Item ti have wrong NBT/Meta values or even wrong IDs

Happens alot with IC² Items but might also be the case with BC Gates. 
Try taking an actual item and plac it in the Crafting Table Templates.

Also remember that the Crafting Pipe needs to be having a fuzzy Upgrade as well.

**Comment by ZZaphodd** [comment]
Yes, I told them the recipe using NEI shift-click.
I followed your comment and it works as I wanted.

And I didn't applied a fuzzy upgrade too. I thought there's separate fuzzy crafting pipe because fuzzy crafting table.

I hope someone have problem like me helps them.
