### ISSUE TITLE
[Request for information] Upgrading modules

### ISSUE THREAD

**Issue by Dijkstra1-zz** [RS485/LogisticsPipes#974]
On the tool tips of some of the upgrades it says they go on modules as well but i can find the way, to did it I have tried applying it to chassis pipe, putting the together in my craft grid (the 2x2 one), I have tried shift right clicking both the upgrade and the module, I have tired using the pipe controller with the module next to in my hot bar (both sides), but I can not work not it out, I must be missing something.

**Comment by hron84** [comment]
Did you tried to use the pipe ctrl on a chassi pipe with module installed?

**Comment by bziemons** [comment]
There is an upgrade for chassis pipes in the making: the upgrade module upgrade (that wasn't me). It does not have a crafting recipe yet, because it is still work in progress, though.

You can upgrade chassis pipes with that and that will allow you to put upgrades on modules in that chassis pipe, just like you would upgrade a normal pipe of that type.
