### ISSUE TITLE
Security Station Improvements

### ISSUE THREAD

**Issue by ruifung** [RS485/LogisticsPipes#98]
- The per user permissions should be in a popup box, similar to that used by the request pipe.
- UI elements should be clarified, the function of the Authorize and Deauthorize buttons aren't clear.
- The "security card" should be automatically inserted and cloned to the entire LP network without user intervention.
- Liquid pipes do not show the "permission denied" message.
- The user list should be replaced with a list of players who are added to the security station, instead of showing the entire list of players who have connected.
- Add a scroll bar to the player list.
- Remove player inventory view, it's doesn't seem like its required at the moment.
- Hide GUID display.
- Protect itself from reconfiguration.

**Comment by davboecki** [comment]
Ok lets go through your list:
- Could be something to discuss, I personaly like it more that it is inside the same gui but a popup would also work quite good.
- Should probably be fixed by the upcoming wiki.
- The security card is automaticly cloned into adjecent pipes from other pipes. It is intentional that you need to inject the first card by hand. That way you can have a security station powered by a network that is not the network that it is protecting.
- Will look into that.
- The input area above the Player list is not only the name of the player being opened but also a search area. It is intended that you have a list of all players. For example when you play with some friends on a server and you set up the security station and your friend isn't there you can't easily add him to the security station if only the names of players who have interacted with the security station are shown. But when all players are shown, then you can search for his name, select him and assign him the rights he needs to continue playing the next time.
- Cause these is a search i don't see the need for a scrollbar / page view.
- Cause of point 2 the inventory is needed for the sec card. 
- That is needed to identify which card belongs to which station.
- Is on our todo list. Probably some sort of configurabe pincode.

**Comment by ruifung** [comment]
But perhaps some additional method of filtering the list then? It would be useful if we could filter based on configured permission. Also the GUI doesn't show fully in gui scale auto, parts of it are offscreen.

**Comment by davboecki** [comment]
What about being able to switch between both lists. One list of all players and one of only those who have interacted with the security station. And about the Gui scale: Looks like i will have to resize the gui => Make the popup for the settings.

**Comment by ruifung** [comment]
Interacted with the security station?

**Comment by AartBluestoke** [comment]
what if using an upgrade on a pipe opened the GUI for the linked security station, rather than the pipe? -- that way the recursive fill results in the same thing?

(relegate the single pipe only effect to shift-clicking or something)

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
