### ISSUE TITLE
No way to upgrade crafting module with advanced sattelite upgrate

### ISSUE THREAD

**Issue by imTheSupremeOne** [RS485/LogisticsPipes#992]
Build: FTB Infinity Evolved: Skyblock.
1) In advanced sattellite upgrade says that u cant apply it to crafting modules, but there is no way to do this old Network Monitor become to LP controller, and its dont have modules upgrade inset.
2) Dont work AE integration - if u place request and provider pipes to ME Interface, I can see all stuff from AE, but I cant see stuff crafing, e.t.c. from AE terminals.

**Comment by SonOfTheStars** [comment]
To No.1:
Module Upgrading is Highly WIP and might not work entirely. If you need help with a particular Setup, feel free to show it and ask for help. We will gladly provid you with our Experience.

To No.2:
You can still request Stuff and it gets made right?
The process not showing is AE's fault because they do not have any handling for the progress providing of LP and only are able to show AE-Internal Processes.

I hope this can help you out!
